// Pure new-profile tests: no oracle assembly/compiler/package/native/network execution.
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readPlan, parseArgs, admitPaths, environment, createReadOnlyFS, flattenEntrypoints, bindingCandidates, resolveLock, snapshot, hash, jsonBytes } from './full-project-common.mjs';
import { nativeArguments, assertNativeSpawn, assertChildEnvironment, awaitExit } from './full-project-preload.mjs';
import { childArgs, assertFrozen } from './run-full-project.mjs';

const plan = readPlan(), oracle = plan.oracle, scratch = 'P:/PiSharp/public-fixtures/semantic-full-test-owned', tests = [];
const test = (name, body) => tests.push({ name, body });
test('scratch is mandatory before any execution', () => assert.throws(() => parseArgs([], plan)));
test('foreign caller task-3 scratch and explicit oracle admitted', () => assert.equal(parseArgs(['--check', '--oracle', oracle, '--scratch', scratch], plan).mode, '--check'));
test('relative scratch rejected', () => assert.throws(() => admitPaths(oracle, './scratch', plan)));
test('scratch cannot be oracle/source/package tree or ancestor', () => { for (const path of [oracle, join(oracle, 'temp'), join(oracle, 'upstream'), join(oracle, '..')]) assert.throws(() => admitPaths(oracle, path, plan)); });
test('foreign oracle rejected', () => assert.throws(() => admitPaths(oracle + '-other', scratch, plan)));
test('unknown/missing/duplicate/conflicting options reject', () => { for (const args of [['--scratch'], ['--scratch', scratch, '--scratch', scratch], ['--scratch', scratch, '--other'], ['--scratch', scratch, '--check', '--capture-new']]) assert.throws(() => parseArgs(args, plan)); });
test('Windows preload file URL preserves spaces and #', () => { const root = 'C:\\review #7\\PiSharp'; const args = childArgs(root); assert.equal(new URL(args[1]).protocol, 'file:'); assert.equal(fileURLToPath(args[1]), join(root, 'tools/SemanticInventory/full-project-preload.mjs')); assert(args[1].includes('%23')); });
test('all mutable environment paths are selected scratch paths', () => { const env = environment(scratch, plan); for (const name of ['HOME', 'USERPROFILE', 'APPDATA', 'LOCALAPPDATA', 'TMP', 'TEMP']) assert(env[name].startsWith(scratch.replaceAll('/', '\\') + '\\')); assert(!Object.hasOwn(env, 'AWS_ACCESS_KEY_ID')); });
test('six Windows home/logon fields are explicit scratch-derived or neutral pins', () => { for (const selected of [scratch, 'D:/authored-caller/scratch']) { const env = environment(selected, plan); assert.equal(env.HOMEDRIVE + env.HOMEPATH, env.HOME); assert.equal(env.HOMEDRIVE, selected.slice(0, 2)); assert.equal(env.SYSTEMDRIVE, 'C:'); assert.equal(env.LOGONSERVER, '\\\\PiSharp-Task'); assert.equal(env.USERDOMAIN, 'PiSharp-Task'); assert.equal(env.USERNAME, 'semantic-profile'); assertChildEnvironment(env, selected, plan); } });
test('injected Windows home/logon field overrides fail with names only', () => { const env = environment(scratch, plan), secret = 'AUTHORED-OVERRIDE-MUST-NOT-BE-LOGGED'; for (const name of ['HOMEDRIVE', 'HOMEPATH', 'LOGONSERVER', 'SYSTEMDRIVE', 'USERDOMAIN', 'USERNAME']) assert.throws(() => assertChildEnvironment({ ...env, [name]: secret }, scratch, plan), error => error.message.includes('key: ' + name) && !error.message.includes(secret)); });
test('child environment rejects inherited credential key and wrong temp', () => { const env = environment(scratch, plan); assertChildEnvironment(env, scratch, plan); assert.throws(() => assertChildEnvironment({ ...env, AWS_ACCESS_KEY_ID: 'authored-test' }, scratch, plan)); assert.throws(() => assertChildEnvironment({ ...env, TEMP: join(oracle, 'temp') }, scratch, plan)); });
test('Windows environment name casing preserves exact pinned values', () => { const env = Object.fromEntries(Object.entries(environment(scratch, plan)).map(([name, value]) => [name.toUpperCase(), value])); assertChildEnvironment(env, scratch, plan); assert.throws(() => assertChildEnvironment({ ...env, TEMP: 'authored-wrong-temp' }, scratch, plan), /key: TEMP/); });
test('ambiguous environment name casing rejects rather than choosing a value', () => { const env = environment(scratch, plan); assert.throws(() => assertChildEnvironment({ ...env, temp: env.TEMP }, scratch, plan), /Ambiguous environment key names/); });
test('unexpected environment diagnostics expose names only and no drive-key exception', () => { const secret = 'AUTHORED-VALUE-MUST-NOT-BE-LOGGED'; for (const name of ['AWS_ACCESS_KEY_ID', '=C:']) { const env = { ...environment(scratch, plan), [name]: secret }; assert.throws(() => assertChildEnvironment(env, scratch, plan), error => error.message.includes(JSON.stringify(name)) && !error.message.includes(secret)); } });
const context = { count: 0, oracle, scratch, exe: join(oracle, plan.native.path), cwd: scratch, hash: plan.native.sha256, expectedHash: plan.native.sha256 }, options = { stdio: ['pipe', 'pipe', 'inherit'] };
test('native source cwd argument is independent from physical scratch cwd', () => assertNativeSpawn(context.exe, nativeArguments(oracle), options, context));
test('wrong exe/hash/argv/second child/current cwd denied', () => { assert.throws(() => assertNativeSpawn(join(scratch, 'wrong.exe'), nativeArguments(oracle), options, context)); assert.throws(() => assertNativeSpawn(context.exe, nativeArguments(oracle), options, { ...context, hash: 'bad' })); assert.throws(() => assertNativeSpawn(context.exe, [...nativeArguments(oracle), '--timing'], options, context)); assert.throws(() => assertNativeSpawn(context.exe, nativeArguments(oracle), options, { ...context, count: 1 })); assert.throws(() => assertNativeSpawn(context.exe, nativeArguments(oracle), options, { ...context, cwd: oracle })); });
test('shell/env/cwd/stdio spawn overrides denied', () => { for (const changed of [{ shell: true }, { env: {} }, { cwd: oracle }, { stdio: 'pipe' }]) assert.throws(() => assertNativeSpawn(context.exe, nativeArguments(oracle), { ...options, ...changed }, context)); });
const source = join(oracle, 'upstream', 'src', 'entry.ts'), vfs = createReadOnlyFS(new Map([[source, Buffer.from('export {};')]]), oracle);
test('owned read remains exact and empty content survives', () => { assert.equal(vfs.fs.readFile(source), 'export {};'); assert.equal(createReadOnlyFS(new Map([[source, Buffer.alloc(0)]]), oracle).fs.readFile(source), ''); });
test('scratch/outside/missing reads deny explicit fallback', () => { for (const path of [join(scratch, 'secret'), join(oracle, '..', 'secret'), join(oracle, 'missing')]) { assert.equal(vfs.fs.readFile(path), null); assert.equal(vfs.fs.fileExists(path), false); assert.equal(vfs.fs.directoryExists(path), false); assert.deepEqual(vfs.fs.getAccessibleEntries(path), { files: [], directories: [] }); } });
test('directory enumeration contains only recorded files', () => assert.deepEqual(vfs.fs.getAccessibleEntries(join(oracle, 'upstream', 'src')), { files: ['entry.ts'], directories: [] }));
test('every export condition/array/null/unknown member stays present', () => { const rows = flattenEntrypoints({ name: 'x', exports: { '.': { types: './dist/x.d.ts', import: ['./dist/x.js', null], custom: './src/x.ts' }, './wild/*': { browser: './dist/*.js' } }, main: './dist/x.js', types: './dist/x.d.ts', bin: { cli: './bin/x.js' } }, 'packages/x/package.json'); assert.equal(rows.length, 8); assert(rows.some(row => row.target === null)); assert(rows.some(row => row.conditions[0] === 'custom')); assert(rows.some(row => row.subpath === './wild/*')); assert(rows.some(row => row.field === 'bin')); });
test('top-level conditional exports and source-only experimental entry retained', () => { const rows = flattenEntrypoints({ name: 'x', exports: { source: './src/index.ts', default: './dist/index.js' } }, 'packages/x/package.json'); assert.equal(rows.length, 2); assert.deepEqual(rows[0].conditions, ['source']); });
test('wildcard reachability keeps unmatched patterns and nested matches', () => { const rows = bindingCandidates({ 'x/*': ['./src/*.ts', './absent/*.ts'], 'x/exact': ['./src/one.ts'] }, ['src/one.ts', 'src/nested/two.ts', 'src/oneXts']); assert.deepEqual(rows[0].patterns[0].matching, ['src/one.ts', 'src/nested/two.ts']); assert.deepEqual(rows[0].patterns[1].matching, []); assert.equal(rows.length, 2); });
const lock = { packages: { 'node_modules/@sdk/a': { version: '2', resolved: 'https://registry.npmjs.org/a', integrity: 'pinned-a', peerDependencies: { z: '*' }, peerDependenciesMeta: { z: { optional: true } } }, 'packages/example/node_modules/@sdk/a': { version: '1', integrity: 'pinned-b' } } };
test('nearest distinct SDK instance is not collapsed to root version', () => { assert.equal(resolveLock(lock, 'packages/example/src/entry.ts', '@sdk/a/subpath').lockEntry.version, '1'); assert.equal(resolveLock(lock, 'packages/other/src/index.ts', '@sdk/a').lockEntry.version, '2'); });
test('lock URL/integrity/optional-peer metadata preserved', () => { const result = resolveLock(lock, 'package.json', '@sdk/a'); assert.equal(result.lockEntry.integrity, 'pinned-a'); assert.equal(result.lockEntry.peerDependenciesMeta.z.optional, true); });
test('builtin/relative/unresolved imports remain explicit kinds', () => { assert.equal(resolveLock(lock, 'x.ts', 'node:fs').kind, 'node-builtin'); assert.equal(resolveLock(lock, 'x.ts', 'fs').kind, 'node-builtin'); assert.equal(resolveLock(lock, 'x.ts', './missing.js').kind, 'relative-or-absolute'); assert.equal(resolveLock(lock, 'x.ts', 'not-installed').kind, 'not-resolved-by-lock'); });
test('snapshot keeps every diagnostic/default/null/undefined/opaque field', () => { const value = { code: 2307, text: 'missing', unknown: null, ownUndefined: undefined, nested: ['1', 1, { opaque: 'x' }] }; assert.deepEqual(snapshot(value, plan.limits), value); });
test('unsupported cycle/nonfinite diagnostics fail with path, never silently filtered', () => { const value = { diagnostic: {} }; value.diagnostic.parent = value; assert.throws(() => snapshot(value, plan.limits), /diagnostic/); assert.throws(() => snapshot({ code: Infinity }, plan.limits), /code/); });
test('immutable expected/harness/receipt mutations reject', () => { const bytes = jsonBytes({ observed: true }), harness = [{ path: 'x', sha256: 'a' }], manifest = { harness, receiptSha256: 'r', expected: { bytes: bytes.length, sha256: hash(bytes) } }; assertFrozen(manifest, bytes, harness, 'r'); assert.throws(() => assertFrozen(manifest, jsonBytes({ observed: false }), harness, 'r')); assert.throws(() => assertFrozen(manifest, bytes, [], 'r')); assert.throws(() => assertFrozen(manifest, bytes, harness, 'different')); });
test('mock child exit awaits actual event without spawning', async () => { const child = new EventEmitter(); child.exitCode = null; child.signalCode = null; child.kill = () => assert.fail('Unexpected kill'); queueMicrotask(() => { child.exitCode = 0; child.emit('exit'); }); assert.equal((await awaitExit(child, 50)).exitAwaited, true); });
test('mock child nonzero/timeout fail', async () => { await assert.rejects(awaitExit({ exitCode: 1, signalCode: null }, 10)); const child = new EventEmitter(); child.exitCode = null; child.signalCode = null; let kills = 0; child.kill = () => kills++; await assert.rejects(awaitExit(child, 1)); assert.equal(kills, 1); });

let passed = 0; const failures = []; for (const { name, body } of tests) { try { await body(); passed++; } catch (error) { failures.push({ name, error: error.message }); } }
console.log(JSON.stringify({ kind: 'pure-unchanged-config-profile-tests', tests: tests.length, passed, failed: failures.length, failures, compilerImported: false, nativeExecuted: false, network: false, originalOracleWrites: false })); if (failures.length) process.exitCode = 1;
