// Pure inert metadata/byte checks. No assembly, extraction, package or compiler API.
import assert from 'node:assert/strict';
import { join } from 'node:path';
import { readPlan, parseArgs, trustedDependencies, regular, confined, hash, jsonBytes, inspectTypeBox, validateManifest, targetPath, admissionRows, admissionRecord, verifyBaseline, context } from './setup-semantic-typebox-declarations.mjs';

const plan = readPlan(), tests = [], test = (name, body) => tests.push({ name, body });
const trusted = await trustedDependencies(plan), compressed = regular(join(plan.archiveSource.root, plan.archiveSource.archive.path));
const observed = inspectTypeBox(compressed, plan, trusted.inspectArchive, trusted.parseJsonSupported), manifest = JSON.parse(observed.evidence.manifest.rawUtf8);
test('only exact canonical new root admitted, default check inert', () => { assert.equal(parseArgs([], plan).mode, '--check'); assert.equal(parseArgs(['--check', '--oracle', plan.oracle], plan).mode, '--check'); assert.throws(() => parseArgs(['--oracle', plan.origin.root], plan)); assert.throws(() => parseArgs(['--oracle', './relative'], plan)); });
test('missing duplicate conflicting unknown setup modes reject', () => { for (const args of [['--oracle'], ['--admit', '--prepare'], ['--check', '--check'], ['--other'], ['--oracle', plan.oracle, '--oracle', plan.oracle]]) assert.throws(() => parseArgs(args, plan)); });
test('confinement rejects traversal, absolute escape and root writes', () => { assert.throws(() => confined(plan.oracle, join(plan.oracle, '..', 'foreign'))); assert.throws(() => confined(plan.oracle, plan.origin.root)); assert.throws(() => confined(plan.oracle, plan.oracle)); assert.equal(confined(plan.oracle, join(plan.oracle, 'archives/x')), join(plan.oracle, 'archives/x')); });
test('real exact archive reinspection retains all1385members and691declarations', () => { assert.equal(observed.evidence.archive.files.length, 1385); assert.equal(observed.evidence.declarationFiles, 691); assert.equal(observed.evidence.runtimeJavaScriptFiles, 691); assert.equal(observed.evidence.packageRuntimeExecuted, false); assert.equal(observed.evidence.archive.sha256, plan.archiveSource.archive.sha256); assert.equal(observed.evidence.actualTypeCheckerTargetSelectionPending, true); });
test('all actual export/type targets preserved, every relative declaration sibling exists', () => { assert.equal(observed.evidence.targets.length, 29); assert.equal(new Set(observed.evidence.targets.filter(row => row.field === 'exports').map(row => row.subpath)).size, 9); assert(observed.evidence.targets.every(row => row.present)); for (const row of observed.evidence.archive.files.filter(row => row.path.endsWith('.mjs'))) assert(observed.parsed.files.has(row.path.replace(/\.mjs$/, '.d.mts'))); });
test('packaged MIT text bytepin retained, no fabricated NOTICE', () => { assert.equal(observed.evidence.notices.length, 1); assert.equal(observed.evidence.notices[0].sha256, plan.package.license.sha256); assert.equal(observed.evidence.notices[0].bytes, 1094); assert(observed.evidence.notices[0].utf8Text.includes('2017-2026 Haydn Paterson')); assert(!observed.parsed.files.has('NOTICE')); });
test('changed compressed bytes fail exact SHA/SRI without parse', () => { const changed = Buffer.from(compressed); changed[20] ^= 1; let called = false; assert.throws(() => inspectTypeBox(changed, plan, () => { called = true; }, trusted.parseJsonSupported)); assert.equal(called, false); });
test('changed archive bytecount and official SRI metadata rejected', () => { for (const mutate of [value => { value.archiveSource.archive.bytes++; }, value => { value.package.lockEntry.integrity = 'wrong'; }, value => { value.archiveSource.archive.sha256 = 'wrong'; }]) { const value = structuredClone(plan); mutate(value); assert.throws(() => inspectTypeBox(compressed, value, trusted.inspectArchive, trusted.parseJsonSupported)); } });
for (const [name, mutate] of [
  ['name', value => { value.name = 'foreign'; }], ['version', value => { value.version = '1.3.28'; }], ['license', value => { value.license = 'UNLICENSED'; }],
  ['new runtime dependency', value => { value.dependencies = { foreign: '*' }; }], ['optional dependency', value => { value.optionalDependencies = { foreign: '*' }; }], ['peer dependency', value => { value.peerDependencies = { foreign: '*' }; }], ['optional peer metadata', value => { value.peerDependenciesMeta = { foreign: { optional: true } }; }],
  ['new bin', value => { value.bin = {}; }], ['install lifecycle', value => { value.scripts = { postinstall: 'foreign' }; }], ['new build script', value => { value.scripts = { build: 'foreign' }; }], ['module type', value => { value.type = 'commonjs'; }],
  ['missing export family', value => { delete value.exports['./error']; }], ['additional export family', value => { value.exports['./foreign'] = value.exports['.']; }], ['missing export condition', value => { delete value.exports['.'].default; }], ['additional export condition', value => { value.exports['.'].types = value.types; }],
  ['missing typesVersion family', value => { delete value.typesVersions['*'].compile; }], ['new typesVersion branch', value => { value.typesVersions['<=5.6'] = {}; }], ['missing actual type target', value => { value.types = './build/missing.d.mts'; }], ['types target traversal', value => { value.types = './../missing.d.mts'; }], ['runtime target traversal', value => { value.module = './../foreign.mjs'; }]
]) test('actual manifest admission rejects changed ' + name, () => { const value = structuredClone(manifest); mutate(value); assert.throws(() => validateManifest(value, observed.parsed.files, plan)); });
test('required target admission rejects glob, drive, backslash, empty and absolute paths', () => { for (const path of ['./build/*', 'C:/foreign', '/foreign', './build\\index.mjs', './', './build/../index.mjs', './build/missing.d.mts']) assert.throws(() => targetPath(path, observed.parsed.files)); });
const parsedMutation = mutate => { const parsed = { ...observed.parsed, files: new Map([...observed.parsed.files].map(([path, bytes]) => [path, Buffer.from(bytes)])) }; mutate(parsed); return () => parsed; };
test('missing packaged declaration target fails before any writes', () => assert.throws(() => inspectTypeBox(compressed, plan, parsedMutation(parsed => parsed.files.delete('build/index.d.mts')), trusted.parseJsonSupported)));
test('new native bytes in inert runtime file fail, rather than skipping member', () => assert.throws(() => inspectTypeBox(compressed, plan, parsedMutation(parsed => parsed.files.set('build/index.mjs', Buffer.from('MZ-authored-test'))), trusted.parseJsonSupported)));
test('invalid UTF8 member and shebang launcher fail', () => { for (const bytes of [Buffer.from([255]), Buffer.from('#!/authored-test')]) assert.throws(() => inspectTypeBox(compressed, plan, parsedMutation(parsed => parsed.files.set('build/index.mjs', bytes)), trusted.parseJsonSupported)); });
test('unknown member type cannot be silently discarded', () => assert.throws(() => inspectTypeBox(compressed, plan, parsedMutation(parsed => { const bytes = parsed.files.get('readme.md'); parsed.files.delete('readme.md'); parsed.files.set('foreign.wasm', bytes); }), trusted.parseJsonSupported)));
test('packaged manifest bytes and full license bytes fail if changed', () => { for (const path of ['package.json', 'license']) assert.throws(() => inspectTypeBox(compressed, plan, parsedMutation(parsed => parsed.files.set(path, Buffer.from('changed'))), trusted.parseJsonSupported)); });
test('compressed expanded/member/count/ratio bounds remain admission blockers', () => { for (const mutate of [value => { value.limits.compressedBytes = 1; }, value => { value.package.regularFiles--; }, value => { value.package.expandedBytes--; }, value => { value.limits.compressionRatio = 1; }, value => { value.limits.memberBytes = 1; }, value => { value.limits.regularTotalBytes = 1; }, value => { value.package.declarationFiles--; }, value => { value.package.runtimeJsFiles--; }]) { const value = structuredClone(plan); mutate(value); assert.throws(() => inspectTypeBox(compressed, value, trusted.inspectArchive, trusted.parseJsonSupported)); } });
const originReceipt = JSON.parse(regular(join(plan.origin.root, plan.origin.receipt)).toString());
test('canonical target combines unchanged2737 with full1385 into exact4122', () => { const files = admissionRows(originReceipt, observed, plan); assert.equal(files.length, 4122); assert.equal(files.filter(row => row.path.startsWith('upstream/node_modules/typebox/')).length, 1385); for (const row of originReceipt.files) assert(files.some(actual => actual.path === row.path && actual.bytes === row.bytes && actual.sha256 === row.sha256)); });
test('duplicate and case-colliding TypeBox payload identities reject', () => { const copied = structuredClone(originReceipt); copied.files[0] = { ...observed.evidence.archive.files[0], path: plan.package.target + '/' + observed.evidence.archive.files[0].path }; assert.throws(() => admissionRows(copied, observed, plan)); copied.files[0].path = copied.files[0].path.toUpperCase(); assert.throws(() => admissionRows(copied, observed, plan)); });
const baseline = trusted.parseJsonSupported(regular(join(import.meta.dirname, '../../fixtures/semantic-full-project-node/expected.json')).toString());
test('actual2496/890baseline qualifies144TypeBoxrecords and all8family counts', () => { assert.deepEqual(verifyBaseline(baseline, plan), { typebox: 129, 'typebox/value': 8, 'typebox/compile': 5, 'typebox/error': 2 }); assert.equal(baseline.diagnostics.getSemanticDiagnostics.length, 2496); });
test('wrong old9784baseline and missing diagnostic family reject', () => { const value = { ...baseline, diagnostics: { ...baseline.diagnostics, getSemanticDiagnostics: [] } }; assert.throws(() => verifyBaseline(value, plan)); delete value.diagnostics.getGlobalDiagnostics; assert.throws(() => verifyBaseline(value, plan)); });
test('changed unresolved candidate version/subpath/index count reject', () => { for (const mutate of [value => value.unresolved.pop(), value => { value.unresolved.find(row => row.parsedSpecifier === 'typebox').nearestLockCandidate.lockEntry.version = 'foreign'; }, value => { value.unresolved.find(row => row.parsedSpecifier === 'typebox').parsedSpecifier = 'foreign'; }]) { const value = structuredClone(baseline); mutate(value); assert.throws(() => verifyBaseline(value, plan)); } });
test('new receipt schema keeps all members/ownership and unresolved semantic gate', () => { const data = { inspected: observed }, files = admissionRows(originReceipt, observed, plan), record = admissionRecord(plan, data, { copiedFiles: originReceipt.files }, files); assert.equal(record.wholePayloadFiles, 4122); assert.equal(record.package.archive.files.length, 1385); assert.equal(record.runtimeJavaScriptRetainedInert, 691); assert.equal(record.packageCodeImported, false); assert.equal(record.semanticPublicClosure, false); assert.deepEqual(record.phaseGatesPassed, []); assert.equal(record.actualNodeBaselineSha256, plan.baseline.snapshotSha256); });
test('complete real old2737/archive/member/installed/license preflight is read-only', async () => { const data = await context(plan); assert.equal(data.origin.receiptSha256, plan.origin.receiptSha256); assert.equal(data.inspected.parsed.files.size, 1385); assert.equal(data.retained.length, 3); });

let passed = 0; const failures = []; for (const { name, body } of tests) { try { await body(); passed++; } catch (error) { failures.push({ name, error: error.message }); } }
console.log(JSON.stringify({ kind: 'pure-inert-TypeBox-stage-B-tests', tests: tests.length, passed, failed: failures.length, failures, network: false, extraction: false, packageCodeImported: false, nativeExecuted: false, oracleWrites: false })); if (failures.length) process.exitCode = 1;
