// Authored inert tests: builtin/trusted repository metadata only; no package/API imports.
import assert from 'node:assert/strict';
import { join } from 'node:path';
import { readPlan, parseArgs, trustedDependencies, regular, confined, hash, inspectLeaf, validateManifest, targetMatches, safeRelative, admissionRows, admissionRecord, verifyBaseline, context, repo } from './setup-semantic-leaf-declarations.mjs';

const plan = readPlan(), trusted = await trustedDependencies(plan), tests = [], test = (name, body) => tests.push({ name, body });
const samples = plan.packages.map(row => { const bytes = regular(join(plan.archiveSource.root, row.archive.path)); return { row, bytes, inspected: inspectLeaf(bytes, row, plan, trusted.inspectArchive, trusted.parseJsonSupported) }; });
const sample = name => samples.find(item => item.row.name === name);
test('default read-only exact root and detached explicit path admitted', () => { assert.equal(parseArgs([], plan).mode, '--check'); assert.equal(parseArgs(['--check', '--oracle', plan.oracle], plan).root.toLowerCase(), plan.oracle.replaceAll('/', '\\').toLowerCase()); assert.throws(() => parseArgs(['--oracle', plan.origin.root], plan)); assert.throws(() => parseArgs(['--oracle', './relative'], plan)); });
test('duplicate missing conflicting and unknown arguments reject', () => { for (const args of [['--oracle'], ['--check', '--admit'], ['--check', '--check'], ['--foreign'], ['--oracle', plan.oracle, '--oracle', plan.oracle]]) assert.throws(() => parseArgs(args, plan)); });
test('owned-path confinement rejects origin, traversal and root writes', () => { for (const path of [plan.oracle, plan.origin.root, join(plan.oracle, '..', 'foreign')]) assert.throws(() => confined(plan.oracle, path)); assert.equal(confined(plan.oracle, join(plan.oracle, 'archives/example')), join(plan.oracle, 'archives/example')); });
test('all seven real archives retain 416 members and 129 declarations', () => { assert.equal(samples.length, 7); assert.equal(samples.reduce((sum, item) => sum + item.inspected.evidence.archive.files.length, 0), 416); assert.equal(samples.reduce((sum, item) => sum + item.inspected.evidence.declarationFiles, 0), 129); for (const { inspected, row } of samples) { assert.equal(inspected.evidence.archive.sha256, row.archive.sha256); assert.equal(inspected.evidence.packageRuntimeExecuted, false); assert.equal(inspected.evidence.allArchiveMembersRetained, true); assert.equal(inspected.evidence.checkerConditionSelectionPending, true); } });
test('all complete actual notices retain pinned text including Marked Markdown BSD', () => { for (const { inspected, row } of samples) assert.deepEqual(inspected.evidence.notices.map(({ utf8Text, ...pin }) => pin), row.notices); assert(sample('marked').inspected.evidence.notices[0].utf8Text.includes('## Markdown')); assert(sample('ignore').inspected.evidence.notices[0].utf8Text.includes('permit persons to whom the Software is')); });
test('actual YAML bin and Marked wrapper/helper shebangs remain exact and inert', () => { assert.deepEqual(sample('yaml').inspected.evidence.retainedShebangPaths, ['bin.mjs']); assert.deepEqual(sample('marked').inspected.evidence.retainedShebangPaths, ['bin/main.js', 'bin/marked.js']); assert.deepEqual(sample('marked').inspected.evidence.retainedInertBins, { marked: 'bin/marked.js' }); for (const item of samples.filter(item => !['yaml', 'marked'].includes(item.row.name))) assert.deepEqual(item.inspected.evidence.retainedShebangPaths, []); });
test('legacy publish lifecycle declarations remain visible rather than called absent', () => { assert.equal(sample('get-east-asian-width').inspected.evidence.scriptDeclarations.prepublish, 'npm run build'); assert.equal(sample('ignore').inspected.evidence.scriptDeclarations.prepublishOnly, 'npm run build'); assert.equal(sample('yaml').inspected.evidence.scriptDeclarations.prepublishOnly, 'npm run clean && npm test && npm run build'); for (const item of samples) assert.equal(item.inspected.evidence.packageRuntimeExecuted, false); });
test('Chalk private imports retain both conditions and actual packaged vendored targets', () => { const rows = sample('chalk').inspected.evidence.targets.filter(row => row.field === 'imports'); assert.equal(rows.length, 3); assert(rows.some(row => row.subpath === '#supports-color' && row.conditions.includes('node'))); assert(rows.some(row => row.subpath === '#supports-color' && row.conditions.includes('default'))); assert(rows.every(row => row.matching.every(path => sample('chalk').inspected.parsed.files.has(path)))); });
test('Diff conditional wildcard and directory exports retain both declaration branches', () => { const rows = sample('diff').inspected.evidence.targets; for (const condition of ['import', 'require']) { const wildcard = rows.find(row => row.subpath === './lib/*.js' && row.conditions.includes(condition) && row.conditions.includes('types')); assert(wildcard && wildcard.matching.length > 0); assert(wildcard.matching.every(path => path.endsWith('.d.ts'))); assert(rows.some(row => row.subpath === './lib/' && row.conditions.includes(condition))); } });
test('strict package target paths reject traversal devices ADS backslashes and missing target', () => { for (const path of ['../foreign', '/foreign', 'C:/foreign', 'x\\foreign', 'x/../foreign', './', 'x/con.txt', 'x/name.', 'x/name ', 'x/file:stream', 'x/?']) assert.throws(() => safeRelative(path)); assert.throws(() => targetMatches('missing.d.ts', sample('chalk').inspected.parsed.files)); assert.throws(() => targetMatches('source/**/index.d.ts', sample('chalk').inspected.parsed.files)); });
test('changed compressed bytes fail pins before archive parser', () => { const { row, bytes } = sample('yaml'), changed = Buffer.from(bytes); changed[20] ^= 1; let parsed = false; assert.throws(() => inspectLeaf(changed, row, plan, () => { parsed = true; }, trusted.parseJsonSupported)); assert.equal(parsed, false); });
test('changed archive count SHA and SRI reject', () => { for (const change of [row => { row.archive.bytes++; }, row => { row.archive.sha256 = 'wrong'; }, row => { row.lockEntry.integrity = 'wrong'; }]) { const row = structuredClone(sample('yaml').row); change(row); assert.throws(() => inspectLeaf(sample('yaml').bytes, row, plan, trusted.inspectArchive, trusted.parseJsonSupported)); } });
for (const [name, mutate] of [
  ['package name', value => { value.name = 'foreign'; }], ['version', value => { value.version = 'foreign'; }], ['license', value => { value.license = 'foreign'; }],
  ['runtime dependency', value => { value.dependencies = { foreign: '*' }; }], ['optional dependency', value => { value.optionalDependencies = { foreign: '*' }; }], ['peer dependency', value => { value.peerDependencies = { foreign: '*' }; }], ['peer metadata', value => { value.peerDependenciesMeta = { foreign: { optional: true } }; }],
  ['unknown bin', value => { value.bin = { foreign: 'dist/index.js' }; }], ['install lifecycle', value => { value.scripts.install = 'foreign'; }], ['prepare lifecycle', value => { value.scripts.prepare = 'foreign'; }],
  ['removed export', value => { delete value.exports['./util']; }], ['new export', value => { value.exports['./foreign'] = './dist/index.js'; }], ['removed type condition', value => { delete value.exports['.'].types; }], ['extra type condition', value => { value.exports['.'].foreign = './dist/index.d.ts'; }], ['present null metadata', value => { value.typesVersions = null; }], ['target traversal', value => { value.main = '../foreign'; }]
]) test('actual manifest mutation rejects ' + name, () => { const item = sample('yaml'), manifest = JSON.parse(item.inspected.evidence.manifest.rawUtf8); mutate(manifest); assert.throws(() => validateManifest(manifest, item.inspected.parsed.files, item.row)); });
test('missing Chalk private import branch cannot disappear', () => { const item = sample('chalk'), manifest = JSON.parse(item.inspected.evidence.manifest.rawUtf8); delete manifest.imports['#supports-color'].default; assert.throws(() => validateManifest(manifest, item.inspected.parsed.files, item.row)); });
const parsedMutation = (item, mutate) => { const parsed = { ...item.inspected.parsed, files: new Map([...item.inspected.parsed.files].map(([path, bytes]) => [path, Buffer.from(bytes)])) }; mutate(parsed); return () => parsed; };
test('missing real declaration target rejects without writing', () => { const item = sample('partial-json'); assert.throws(() => inspectLeaf(item.bytes, item.row, plan, parsedMutation(item, parsed => parsed.files.delete('dist/index.d.ts')), trusted.parseJsonSupported)); });
test('changed binary UTF8 unapproved shebang and regular member cannot be accepted', () => { const item = sample('ignore'); for (const bytes of [Buffer.from('MZ-authored-probe'), Buffer.from([255]), Buffer.from('#!/foreign'), Buffer.from('authored changed bytes')]) assert.throws(() => inspectLeaf(item.bytes, item.row, plan, parsedMutation(item, parsed => parsed.files.set('index.js', bytes)), trusted.parseJsonSupported)); });
test('new traversal or case-colliding member fails complete exact fingerprint', () => { const item = sample('ignore'); for (const path of ['../foreign.js', 'INDEX.JS']) assert.throws(() => inspectLeaf(item.bytes, item.row, plan, parsedMutation(item, parsed => { const bytes = parsed.files.get('index.js'); parsed.files.delete('index.js'); parsed.files.set(path, bytes); }), trusted.parseJsonSupported)); });
test('changed manifest and notice bytes cannot survive full archive validation', () => { const item = sample('ignore'); for (const path of ['package.json', 'LICENSE-MIT']) assert.throws(() => inspectLeaf(item.bytes, item.row, plan, parsedMutation(item, parsed => parsed.files.set(path, Buffer.from('changed'))), trusted.parseJsonSupported)); });
test('approved Marked helper does not permit changed bytes or arbitrary launcher paths', () => { const item = sample('marked'); assert.throws(() => inspectLeaf(item.bytes, item.row, plan, parsedMutation(item, parsed => parsed.files.set('bin/main.js', Buffer.from('#!/usr/bin/env node\nforeign'))), trusted.parseJsonSupported)); assert.throws(() => inspectLeaf(item.bytes, item.row, plan, parsedMutation(item, parsed => { const bytes = parsed.files.get('bin/main.js'); parsed.files.delete('bin/main.js'); parsed.files.set('bin/foreign.js', bytes); }), trusted.parseJsonSupported)); });
test('compressed expanded ratio member total and declaration bounds reject', () => { const item = sample('diff'); for (const mutate of [p => { p.limits.compressedBytes = 1; }, p => { p.limits.expandedBytes = 1; }, p => { p.limits.compressionRatio = 1; }, p => { p.limits.memberBytes = 1; }, p => { p.limits.regularTotalBytes = 1; }]) { const p = structuredClone(plan); mutate(p); assert.throws(() => inspectLeaf(item.bytes, item.row, p, trusted.inspectArchive, trusted.parseJsonSupported)); } const row = structuredClone(item.row); row.declarationFiles--; assert.throws(() => inspectLeaf(item.bytes, row, plan, trusted.inspectArchive, trusted.parseJsonSupported)); });
const origin = JSON.parse(regular(join(plan.origin.root, plan.origin.receipt)).toString('utf8'));
test('all 4122 original members remain byte-identical in 4538-member projection', () => { const files = admissionRows(origin, samples.map(item => item.inspected)); assert.equal(files.length, 4538); for (const row of origin.files) assert(files.some(file => file.path === row.path && file.bytes === row.bytes && file.sha256 === row.sha256)); });
test('duplicate and case-colliding new package identity reject', () => { const copied = structuredClone(origin), first = samples[0].inspected.evidence; copied.files[0] = { ...first.archive.files[0], path: first.target + '/' + first.archive.files[0].path }; assert.throws(() => admissionRows(copied, samples.map(item => item.inspected))); copied.files[0].path = copied.files[0].path.toUpperCase(); assert.throws(() => admissionRows(copied, samples.map(item => item.inspected))); });
const baseline = trusted.parseJsonSupported(regular(join(repo, plan.baseline.pins[0].path)).toString('utf8'));
test('genuine 2318/746 baseline includes all eight families and exact 35 leaf records', () => { assert.deepEqual(verifyBaseline(baseline, plan), plan.baseline.leafSpecifierCounts); assert.equal(baseline.mandatoryBaselineLockInstances.length, 34); assert.equal(baseline.unresolved.length, 746); });
test('wrong predecessor count or dropped diagnostic family rejects', () => { const value = { ...baseline, diagnostics: { ...baseline.diagnostics, getSemanticDiagnostics: [] } }; assert.throws(() => verifyBaseline(value, plan)); delete value.diagnostics.getGlobalDiagnostics; assert.throws(() => verifyBaseline(value, plan)); });
test('authored receipt preserves seven raw manifests all notices and inert-policy flags', () => { const data = { inspected: samples.map(item => item.inspected) }, files = admissionRows(origin, data.inspected), value = admissionRecord(plan, data, { authoredProbe: true }, files); assert.equal(value.packages.length, 7); assert.equal(value.files.length, 4538); assert.equal(value.newDeclarationFiles, 129); assert.equal(value.nativeExecuted, false); assert.equal(value.packageCodeImported, false); assert.equal(value.allArchiveMembersRetained, true); assert.equal(value.binLinks, false); assert.equal(value.semanticPublicClosure, false); assert.deepEqual(value.phaseGatesPassed, []); });
test('qualified original full receipt and all installed-to-archive members reverify read-only', async () => { const data = await context(plan); assert.equal(data.origin.receiptSha256, plan.origin.receiptSha256); assert.equal(data.origin.receipt.files.length, 4122); assert.equal(data.inspected.length, 7); assert.equal(data.retained.length, 16); });

let passed = 0; for (const { name, body } of tests) { try { await body(); passed++; } catch (error) { console.error(name + ': ' + error.stack); process.exitCode = 1; } } console.log(JSON.stringify({ scope: 'inert-existing-leaf-archive-admission-tests', passed, failed: tests.length - passed, total: tests.length, compilerExecuted: false, packageRuntimeExecuted: false, archiveExtracted: false }));
