// Pure/inert tests. No extraction, oracle assembly, package API/native/network.
import assert from 'node:assert/strict';
import { gzipSync } from 'node:zlib';
import { readPlan, trustedDependencies, acquisitionFiles, inspectDeclarationArchive, parseArgs, confined, declarationCandidates, hash, jsonBytes } from './setup-semantic-node-declarations.mjs';

const plan = readPlan(), deps = await trustedDependencies(plan), tests = [];
const test = (name, body) => tests.push({ name, body });
function checksum(header) { header.fill(32, 148, 156); const sum = header.reduce((a, b) => a + b, 0); header.write(sum.toString(8).padStart(6, '0') + '\0 ', 148, 'ascii'); }
function tar(members, root, change = () => {}) {
  const chunks = [];
  members.forEach((row, index) => { const header = Buffer.alloc(512), content = Buffer.isBuffer(row.content) ? row.content : Buffer.from(row.content ?? ''); assert(Buffer.byteLength(row.path) < 100); header.write(row.path); header.write('0000644\0', 100, 'ascii'); header.write(content.length.toString(8).padStart(11, '0') + '\0', 124, 'ascii'); header.write(row.type ?? '0', 156, 'ascii'); header.write('ustar\0' + '00', 257, 'ascii'); if (root === 'node v22.19') { header.write('00000000001\0', 476, 'ascii'); header.write('00000000001\0', 488, 'ascii'); } change(header, index); checksum(header); chunks.push(header, content, Buffer.alloc((512 - content.length % 512) % 512)); });
  return Buffer.concat([...chunks, Buffer.alloc(1024)]);
}
function packed(members, root = 'package', change) { return gzipSync(tar(members, root, change)); }
const license = 'Copyright authored test\nPermission is hereby granted, free of charge, to any person.\nTHE SOFTWARE IS PROVIDED AS IS.\n';
function packageFixture(row, overrides = {}, extras = [], rawManifest) {
  const manifest = { name: row.name, version: row.lockEntry.version, license: row.lockEntry.license, types: 'index.d.ts', ...(row.lockEntry.dependencies ? { dependencies: row.lockEntry.dependencies } : {}), ...overrides };
  return packed([{ path: row.admittedArchiveRoot + '/package.json', content: rawManifest ?? JSON.stringify(manifest) }, { path: row.admittedArchiveRoot + '/index.d.ts', content: '/// <reference lib="esnext.disposable" />\nexport interface X { value: string }\n' }, { path: row.admittedArchiveRoot + '/LICENSE', content: license }, ...extras], row.admittedArchiveRoot);
}
function syntheticRow(row, bytes) { return { ...row, lockEntry: { ...row.lockEntry, integrity: 'sha512-' + hash(bytes, 'sha512', 'base64') }, acquired: { bytes: bytes.length, sha256: hash(bytes) } }; }
function inspectFixture(row, bytes, caps = plan.limits) { return inspectDeclarationArchive(bytes, syntheticRow(row, bytes), caps, deps.inspectArchive, deps.parseJsonSupported); }

test('default check is read-only and detached explicit exact oracle admitted', () => { assert.equal(parseArgs([], plan).mode, '--check'); assert.equal(parseArgs(['--check', '--oracle', plan.oracle], plan).root.toLowerCase(), plan.oracle.replaceAll('/', '\\').toLowerCase()); });
test('unknown/duplicate/conflicting/missing/foreign paths reject', () => { for (const args of [['--restore'], ['--oracle'], ['--check', '--admit'], ['--oracle', plan.oracle, '--oracle', plan.oracle], ['--oracle', plan.oracle + '-foreign']]) assert.throws(() => parseArgs(args, plan)); });
test('confinement rejects parent/absolute other-drive/root writes', () => { for (const path of [plan.oracle, plan.oracle + '/../outside', 'D:/outside']) assert.throws(() => confined(plan.oracle, path)); });
test('reviewed original helpers and raw JSON dependency hashes remain exact', () => assert.equal(plan.dependencies.length, 6));
test('actual acquired archives inspected inertly twice with complete identical evidence', () => { const acquired = acquisitionFiles(plan, deps.parseJsonSupported); for (const row of plan.packages) { const bytes = acquired.find(file => file.path === row.archivePath).bytes, first = inspectDeclarationArchive(bytes, row, plan.limits, deps.inspectArchive, deps.parseJsonSupported), second = inspectDeclarationArchive(bytes, row, plan.limits, deps.inspectArchive, deps.parseJsonSupported); assert(jsonBytes(first.evidence).equals(jsonBytes(second.evidence))); assert.equal(first.evidence.archive.files.length, row.name === '@types/node' ? 73 : 41); assert.equal(first.evidence.declarations.length, row.name === '@types/node' ? 70 : 38); assert.equal(first.evidence.notices.length, 1); assert.equal(first.evidence.rootNoticePresent, false); assert.equal(first.evidence.typeReferenceSemanticClosure, false); } });
test('actual Node typesVersions and Undici absence remain exact', () => { const acquired = acquisitionFiles(plan, deps.parseJsonSupported), rows = plan.packages.map(row => inspectDeclarationArchive(acquired.find(file => file.path === row.archivePath).bytes, row, plan.limits, deps.inspectArchive, deps.parseJsonSupported)); assert.deepEqual(rows[0].evidence.manifest.entryFields.find(row => row.name === 'typesVersions').value, { '<=5.6': { '*': ['ts5.6/*'] } }); assert.equal(rows[1].evidence.manifest.entryFields.find(row => row.name === 'typesVersions').present, false); });
test('lexical triple slash/module candidates carry exact offsets and unresolved scope', () => { const text = '/// <reference path="./x.d.ts" />\nimport("undici-types");\nexport { X } from "node:fs";'; const value = declarationCandidates('index.d.ts', text); assert.equal(value.candidates.length, 3); assert.equal(value.candidates[0].specifier, './x.d.ts'); assert.equal(value.candidates[1].offsetUtf16, text.indexOf('import')); assert.equal(value.lexicalOnly, true); assert.equal(value.exhaustiveSemanticResolution, false); });

for (const row of plan.packages) {
  const root = row.admittedArchiveRoot, bytes = packageFixture(row);
  test(row.name + ' required entry/default/license fields accepted from authored fixture', () => { const value = inspectFixture(row, bytes); assert.equal(value.evidence.manifest.entryFields.find(row => row.name === 'types').value, 'index.d.ts'); assert.equal(value.evidence.archive.admittedRoot, root); });
  test(row.name + ' SRI/sha256/size mutations reject', () => { for (const changed of [{ ...row, acquired: { ...row.acquired, sha256: 'wrong' } }, { ...syntheticRow(row, bytes), acquired: { bytes: bytes.length + 1, sha256: hash(bytes) } }, { ...syntheticRow(row, bytes), lockEntry: { ...row.lockEntry, integrity: 'wrong' } }]) assert.throws(() => inspectDeclarationArchive(bytes, changed, plan.limits, deps.inspectArchive, deps.parseJsonSupported)); });
  for (const [name, override] of [['version', { version: '0.0.0' }], ['name', { name: 'foreign' }], ['license', { license: 'unknown' }], ['bin', { bin: 'index.d.ts' }], ['lifecycle', { scripts: { install: 'authored-no-execution' } }], ['entry missing', { types: 'absent.d.ts' }], ['dependency changed', { dependencies: { foreign: '*' } }]]) test(row.name + ' changed ' + name + ' rejects', () => assert.throws(() => inspectFixture(row, packageFixture(row, override))));
  test(row.name + ' duplicate JSON manifest rejects', () => assert.throws(() => inspectFixture(row, packageFixture(row, {}, [], '{"name":"x","name":"y"}'))));
  test(row.name + ' new binary/native payload rejects', () => assert.throws(() => inspectFixture(row, packageFixture(row, {}, [{ path: root + '/inert-data', content: Buffer.from([0, 97, 115, 109]) }]))));
  test(row.name + ' invalid UTF8 member content rejects', () => assert.throws(() => inspectFixture(row, packageFixture(row, {}, [{ path: root + '/data.txt', content: Buffer.from([0xc3, 0x28]) }]))));
  test(row.name + ' compressed/expanded/member/count/ratio bounds reject', () => { for (const caps of [{ ...plan.limits, compressedBytes: 1 }, { ...plan.limits, expandedBytes: 1 }, { ...plan.limits, memberBytes: 1 }, { ...plan.limits, members: 1 }, { ...plan.limits, compressionRatio: 0.01 }]) assert.throws(() => inspectFixture(row, bytes, caps)); });
  const badNames = [['absolute', '/' + root + '/x'], ['traversal', root + '/../x'], ['backslash', root + '\\x'], ['ADS', root + '/x:stream'], ['device-name', root + '/CON.txt'], ['trailing-dot', root + '/x.'], ['wrong-prefix', (root === 'package' ? 'node v22.19' : 'package') + '/x']];
  for (const [name, path] of badNames) test(row.name + ' tar ' + name + ' rejects', () => assert.throws(() => deps.inspectArchive(packed([{ path, content: 'x' }], root), plan.limits, root)));
  for (const [name, members] of [['duplicate', [{ path: root + '/x' }, { path: root + '/x' }]], ['case-collision', [{ path: root + '/X' }, { path: root + '/x' }]], ['file-parent', [{ path: root + '/x' }, { path: root + '/x/y' }]]]) test(row.name + ' tar ' + name + ' rejects', () => assert.throws(() => deps.inspectArchive(packed(members, root), plan.limits, root)));
  for (const type of ['1', '2', '3', '4', '6', 'g', 'L', 'S']) test(row.name + ' tar unsupported type ' + type + ' rejects', () => assert.throws(() => deps.inspectArchive(packed([{ path: root + '/x', type }], root), plan.limits, root)));
  test(row.name + ' corrupted checksum and incomplete terminal reject', () => { const valid = tar([{ path: root + '/x', content: 'x' }], root), altered = Buffer.from(valid); altered[0] ^= 1; assert.throws(() => deps.inspectArchive(gzipSync(altered), plan.limits, root)); assert.throws(() => deps.inspectArchive(gzipSync(valid.subarray(0, valid.length - 1024)), plan.limits, root)); });
  test(row.name + ' hidden bytes after NUL name and regular-link target reject', () => { for (const change of [header => { header[90] = 120; }, header => { header.write('target', 157); }]) assert.throws(() => deps.inspectArchive(packed([{ path: root + '/x' }], root, change), plan.limits, root)); });
}
for (const [name, change] of [['magic', h => h[257] = 120], ['prefix-NUL', h => h[360] = 120], ['separator', h => h[475] = 1], ['time-nonoctal', h => h[476] = 56], ['reserved-tail', h => h[500] = 1]]) test('Node observed time-header layout invalid ' + name + ' rejects', () => assert.throws(() => deps.inspectArchive(packed([{ path: 'node v22.19/x' }], 'node v22.19', change), plan.limits, 'node v22.19')));
test('unknown publisher root is rejected without prefix adaptation', () => assert.throws(() => deps.inspectArchive(packed([{ path: 'foreign/x' }]), plan.limits, 'foreign')));

let passed = 0; const failures = []; for (const { name, body } of tests) { try { await body(); passed++; } catch (error) { failures.push({ name, error: error.message }); } }
console.log(JSON.stringify({ kind: 'pure-inert-two-declaration-archive-admission-tests', tests: tests.length, passed, failed: failures.length, failures, archivesExtracted: false, oraclePrepared: false, compilerImported: false, nativeExecuted: false, processes: false, network: false })); if (failures.length) process.exitCode = 1;
