using System.Collections.Immutable;
using System.Net;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using PiSharp.AI;
using PiSharp.AI.Protocols.GoogleGenerativeAI;
using PiSharp.Agent;
using PiSharp.Contracts;
using NativeAgent = PiSharp.Agent.Agent;

// Authored offline cases. Expected classifications are literal fixtures, not SDK captures
// or values generated by the implementation's diagnostic mapping.
internal static class GoogleNativeDiagnosticCases
{
    private static readonly ModelDescriptor Model = new("gemini-3-flash-preview", "google-generative-ai", "google");
    private const string PrivateText = "inert-private-sentinel-MalformedStream-ResourceLimit-ProviderError";
    private const string ToolChunk = """{"responseId":"owned-response","candidates":[{"content":{"parts":[{"functionCall":{"id":"owned-call","name":"inspect","args":{"value":7,"keep":null}},"thoughtSignature":"c2ln"}]},"finishReason":"STOP"}],"usageMetadata":{"promptTokenCount":11,"cachedContentTokenCount":3,"candidatesTokenCount":2,"thoughtsTokenCount":4,"totalTokenCount":17}}""";
    private const string TextChunk = """{"candidates":[{"content":{"parts":[{"text":"owned text"}]},"finishReason":"STOP"}]}""";
    private static readonly JsonData Metadata = JsonData.Parse("""{"type":"chat","id":"gemini-3-flash-preview","api":"google-generative-ai","provider":"google","name":"authored","baseUrl":"https://google.invalid/v1beta","reasoning":true,"input":["text","image"],"contextWindow":100000,"maxTokens":1000,"cost":{"input":2,"output":3,"cacheRead":0.5,"cacheWrite":0}}""");
    private static readonly TimeSpan Deadline = TimeSpan.FromSeconds(5);
    internal static IEnumerable<(string Id, Func<Task> Run)> Cases()
    {
        yield return ("google.native-diagnostics-real-producer-matrix", ProducerMatrix);
        yield return ("google.native-diagnostics-primary-held-cleanup", HeldCleanup);
        yield return ("google.native-diagnostics-cancellation-physical-joins", CancellationJoins);
        yield return ("google.native-diagnostics-terminal-callbacks", TerminalCallbacks);
        yield return ("google.native-diagnostics-shared-fallback-and-domain", SharedFallback);
        yield return ("google.native-diagnostics-post-terminal-cleanup", PostTerminalCleanup);
        yield return ("google.native-diagnostics-actual-agent-authority", AgentAuthority);
        yield return ("google.native-diagnostics-exact-api-and-wire-controls", ApiAndWireControls);
    }
    private static GoogleGenerativeAIOptions Options() => new(Metadata, PrivateText);
    private static ImmutableArray<TranscriptEntry> Inputs() => [
        new("system", JsonData.Parse("""{"role":"system","content":"base","toolsAdded":[{"name":"inspect","parameters":{"type":"object","properties":{"value":{"type":"number"},"keep":{"type":"null"}},"required":["value"]}}],"timestamp":123}""")),
        new("user", JsonData.Parse("""{"role":"user","content":"hello","timestamp":123}"""))];
    private static ChatRequest Request() => new(Model, Inputs(), 123);
    private static string Wire(string chunk) => "data: " + chunk + "\n\n";
    private static TaskCompletionSource Gate() => new(TaskCreationOptions.RunContinuationsAsynchronously);
    private static void Check(bool value, string message) { if (!value) throw new InvalidOperationException(message); }
    private static void Equal<T>(T expected, T actual) => Check(EqualityComparer<T>.Default.Equals(expected, actual), $"Expected {expected}, got {actual}.");
    private static NativeChatDiagnostic Diagnostic(NativeChatFailureCode code) => new(NativeChatAdapter.GoogleGenerativeAI, code);
    private static async Task Join(Task task) { try { await task; } catch { } }
    private static async Task<StreamTerminalEvent> Drain(IAsyncEnumerable<StreamEvent> events)
    {
        StreamTerminalEvent? terminal = null; var count = 0;
        await foreach (var value in events)
            if (value is StreamTerminalEvent end) { terminal = end; count++; }
        Equal(1, count); return terminal ?? throw new InvalidOperationException("Missing terminal.");
    }
    private static void AssertTerminal(StreamTerminalEvent terminal, NativeChatFailureCode? primary, bool cleanup,
        ChatResult? result = null, StopReason? reason = null)
    {
        var expectedPrimary = primary is { } code ? Diagnostic(code) : null;
        var expectedCleanup = cleanup ? Diagnostic(NativeChatFailureCode.CleanupFailed) : null;
        Equal(expectedPrimary, terminal.NativeDiagnostic); Equal(expectedCleanup, terminal.NativeCleanupDiagnostic);
        if (reason is { } stop) Equal(stop, terminal.Reason);
        Equal(terminal.Reason, terminal.Message.StopReason);
        Check((primary is null) == (terminal is StreamDone), "Failure gained a successful terminal.");
        if (result is not null)
        {
            Equal(expectedPrimary, result.NativeDiagnostic); Equal(expectedCleanup, result.NativeCleanupDiagnostic);
            Equal(expectedPrimary, result.Failure?.NativeDiagnostic);
            Check((primary is null) == (result.Failure is null), "Terminal/result failure disagreement.");
            Same(PiWireJson.WriteMessage(terminal.Message), PiWireJson.WriteMessage(result.Message));
            if (primary == NativeChatFailureCode.Cancelled) Equal(ChatFailureKind.Cancelled, result.Failure!.Kind);
        }
        var plain = terminal with { NativeDiagnostic = null, NativeCleanupDiagnostic = null };
        Same(PiWireJson.WriteEvent(plain), PiWireJson.WriteEvent(terminal));
        var roundTrip = PiWireJson.ReadEvent(PiWireJson.WriteEvent(terminal).Value) as StreamTerminalEvent;
        Check(roundTrip is not null && roundTrip.NativeDiagnostic is null && roundTrip.NativeCleanupDiagnostic is null,
            "Native diagnostics entered Pi event wire.");
        var text = PiWireJson.WriteEvent(terminal).ToString();
        Check(!text.Contains("nativeDiagnostic", StringComparison.OrdinalIgnoreCase) &&
            !text.Contains("nativeCleanupDiagnostic", StringComparison.OrdinalIgnoreCase) &&
            !text.Contains(PrivateText, StringComparison.Ordinal), "Native/private fields entered Pi wire.");
        if (result?.Failure is { } failure)
            Check(!failure.Message.Contains(PrivateText, StringComparison.Ordinal), "Shared failure leaked private text.");
    }
    private static void Same(JsonData expected, JsonData actual) =>
        Check(JsonElement.DeepEquals(expected.Value, actual.Value), "Pi wire differs.");

    private static async Task ProducerMatrix()
    {
        var fixture = JsonData.Parse(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "native-diagnostic-cases.json")));
        Equal(20, fixture.Value.GetProperty("producerVectors").GetArrayLength());
        foreach (var vector in fixture.Value.GetProperty("producerVectors").EnumerateArray())
        foreach (var shared in new[] { false, true })
        {
            var scenario = vector.GetProperty("scenario").GetString()!;
            NativeChatFailureCode? expected = vector.GetProperty("code").ValueKind == JsonValueKind.Null ? null :
                Enum.Parse<NativeChatFailureCode>(vector.GetProperty("code").GetString()!);
            var body = new OwnedBody(Wire(TextChunk));
            var options = Options(); var request = Request(); var status = HttpStatusCode.OK;
            switch (scenario)
            {
                case "tool-success": body = new(Wire(ToolChunk)); break;
                case "provider-finish": body = new(Wire(ToolChunk.Replace("\"STOP\"", "\"SAFETY\"", StringComparison.Ordinal))); break;
                case "provider-error-chunk": body = new(Wire("""{"error":{"message":"not copied"}}""")); break;
                case "http-error": body = new(PrivateText); status = HttpStatusCode.BadRequest; break;
                case "invalid-json": body = new("data: {bad}\n\n"); break;
                case "invalid-shape": body = new(Wire("""{"candidates":{}}""")); break;
                case "invalid-tool-args": body = new(Wire(ToolChunk.Replace("""{"value":7,"keep":null}""", "[]", StringComparison.Ordinal))); break;
                case "missing-finish": body = new(Wire(TextChunk.Replace(",\"finishReason\":\"STOP\"", "", StringComparison.Ordinal))); break;
                case "frame-limit": options = options with { MaximumFrameCharacters = 8 }; break;
                case "unsupported-usage": body = new(Wire(ToolChunk.Replace("\"promptTokenCount\":11", "\"promptTokenCount\":0.5", StringComparison.Ordinal))); break;
                case "read-fault": body.FailRead = true; break;
                case "missing-key": options = options with { ApiKey = "" }; break;
                case "configuration": request = request with { Model = Model with { Id = "mismatch" } }; break;
                case "unsupported-header": options = options with { Headers = JsonData.Parse("""{"x-authored":7}""") }; break;
                case "payload-fault": options = options with { Hooks = new() { OnPayload = (_, _, _) => throw new IOException(PrivateText) } }; break;
                case "typed-payload-limit": options = options with { Hooks = new() { OnPayload = (_, _, _) =>
                    throw new GoogleGenerativeAIException(GoogleFailure.ResourceLimit, "Authored typed resource failure.") } }; break;
                case "provider-hook-fault": options = options with { Hooks = new() { OnProviderStreamEvent = (_, _, _) => throw new IOException(PrivateText) } }; break;
                case "response-hook-fault": options = options with { Hooks = new() { OnNativeResponse = (_, _, _) => throw new IOException(PrivateText) } }; break;
                case "send-fault": break;
                case "text-success": break;
                default: throw new InvalidOperationException("Unknown authored vector.");
            }
            var sends = 0;
            using var handler = new Handler((_, _) => { sends++;
                if (scenario == "send-fault") throw new IOException(PrivateText);
                return Task.FromResult(Response(body, status)); });
            using var client = new HttpClient(handler);
            var transport = new GoogleGenerativeAIHttpTransport(client, Model, options);
            ChatResult? result = null; StreamTerminalEvent terminal;
            if (shared)
            {
                await using var run = await new ChatClient(transport, 1).StartAsync(request);
                terminal = await Drain(run.ReadEventsAsync()); result = await run.Completion;
            }
            else terminal = await Drain(transport.StreamAsync(request));
            AssertTerminal(terminal, expected, false, result);
            Equal(vector.GetProperty("sends").GetInt32(), sends);
            Check(!handler.Disposed, "Borrowed HTTP client was disposed.");
            if (sends != 0 && scenario != "send-fault")
                Check(scenario == "response-hook-fault" ? body.SyncDisposed : body.AsyncDisposed, "Original response/body cleanup was not joined.");
        }
    }

    private static async Task HeldCleanup()
    {
        foreach (var scenario in new[] { "provider", "malformed", "eof", "stop", "tool", "length" })
        foreach (var fail in new[] { false, true })
        foreach (var shared in new[] { false, true })
        {
            var wire = scenario switch {
                "provider" => Wire(ToolChunk.Replace("\"STOP\"", "\"SAFETY\"", StringComparison.Ordinal)),
                "malformed" => Wire(ToolChunk) + "data: {bad}\n\n",
                "eof" => Wire(ToolChunk.Replace(",\"finishReason\":\"STOP\"", "", StringComparison.Ordinal)),
                "length" => Wire(ToolChunk.Replace("\"STOP\"", "\"MAX_TOKENS\"", StringComparison.Ordinal)),
                "stop" => Wire(TextChunk), _ => Wire(ToolChunk) };
            NativeChatFailureCode? expected = scenario switch {
                "provider" => NativeChatFailureCode.ProviderError, "malformed" => NativeChatFailureCode.MalformedStream,
                "eof" => NativeChatFailureCode.UnexpectedEof, _ => fail ? NativeChatFailureCode.CleanupFailed : null };
            var body = new OwnedBody(wire) { HoldCleanup = true, FailCleanup = fail };
            using var handler = new Handler((_, _) => Task.FromResult(Response(body)));
            using var client = new HttpClient(handler);
            var transport = new GoogleGenerativeAIHttpTransport(client, Model, Options());
            ChatRun? run = null; Task<StreamTerminalEvent>? original = null;
            try
            {
                if (shared) run = await new ChatClient(transport, 1).StartAsync(Request());
                original = Drain(shared ? run!.ReadEventsAsync() : transport.StreamAsync(Request()));
                await body.CleanupEntered.Task.WaitAsync(Deadline);
                Check(!original.IsCompleted && (run is null || !run.Completion.IsCompleted), "Held cleanup published settlement.");
                body.ReleaseCleanup.TrySetResult(); var terminal = await original;
                var result = run is null ? null : await run.Completion;
                AssertTerminal(terminal, expected, fail, result);
                if (scenario != "stop")
                {
                    Equal(17L, terminal.Message.Usage.TotalTokens);
                    Equal("owned-call", terminal.Message.Content.OfType<ToolCallContent>().Single().Id);
                    Equal(7, terminal.Message.Content.OfType<ToolCallContent>().Single().Arguments.Value.GetProperty("value").GetInt32());
                    Equal("owned-response", terminal.Message.ExtraProperties!.Values["responseId"].Value.GetString());
                }
                if (scenario == "provider")
                {
                    var extra = terminal.Message.ExtraProperties ?? throw new InvalidOperationException("Missing provider properties.");
                    Equal("SAFETY", extra.Values["rawStopReason"].Value.GetString());
                    Equal("Provider stopped with: SAFETY", extra.Values["errorMessage"].Value.GetString());
                }
                Check(body.AsyncDisposed && !handler.Disposed, "Held release ownership did not settle.");
            }
            finally { body.ReleaseCleanup.TrySetResult(); if (original is not null) await Join(original); if (run is not null) await run.DisposeAsync(); }
        }
    }

    private static async Task CancellationJoins()
    {
        foreach (var seam in new[] { "read", "provider", "response", "cleanup" })
        foreach (var failCleanup in new[] { false, true })
        foreach (var shared in new[] { false, true })
        {
            using var cancellation = new CancellationTokenSource();
            var entered = Gate(); var release = Gate();
            var body = new OwnedBody(Wire(ToolChunk)) { HoldCleanup = true, FailCleanup = failCleanup };
            var options = Options();
            if (seam == "read") { body.ReadEntered = entered; body.ReleaseRead = release; }
            if (seam == "provider") options = options with { Hooks = new() { OnProviderStreamEvent = async (_, _, _) =>
                { entered.TrySetResult(); await release.Task; } } };
            if (seam == "response") options = options with { Hooks = new() { OnNativeResponse = async (_, _, _) =>
                { entered.TrySetResult(); await release.Task; } } };
            if (seam == "response") body.FailSyncCleanup = failCleanup;
            using var handler = new Handler((_, _) => Task.FromResult(Response(body)));
            using var client = new HttpClient(handler);
            var transport = new GoogleGenerativeAIHttpTransport(client, Model, options);
            ChatRun? run = null; Task<StreamTerminalEvent>? original = null;
            try
            {
                if (shared) run = await new ChatClient(transport, 1).StartAsync(Request(), cancellation.Token);
                original = Drain(shared ? run!.ReadEventsAsync() : transport.StreamAsync(Request(), cancellation.Token));
                await (seam == "cleanup" ? body.CleanupEntered.Task : entered.Task).WaitAsync(Deadline);
                cancellation.Cancel();
                Check(!original.IsCompleted && (run is null || !run.Completion.IsCompleted), "Cancellation detached an original task.");
                release.TrySetResult();
                if (seam != "response")
                {
                    await body.CleanupEntered.Task.WaitAsync(Deadline);
                    Check(!original.IsCompleted && (run is null || !run.Completion.IsCompleted), "Cancellation skipped held cleanup.");
                }
                body.ReleaseCleanup.TrySetResult(); var terminal = await original;
                AssertTerminal(terminal, NativeChatFailureCode.Cancelled, failCleanup, run is null ? null : await run.Completion, StopReason.Aborted);
                Check((seam == "response" ? body.SyncDisposed : body.AsyncDisposed) && !handler.Disposed, "Cancellation retained physical ownership.");
            }
            finally { release.TrySetResult(); body.ReleaseCleanup.TrySetResult(); if (original is not null) await Join(original); if (run is not null) await run.DisposeAsync(); }
        }
    }

    private static async Task TerminalCallbacks()
    {
        foreach (var seam in new[] { "settlement", "publication" })
        foreach (var cancel in new[] { false, true })
        foreach (var failCleanup in new[] { false, true })
        foreach (var shared in new[] { false, true })
        foreach (var settleAbort in new[] { false, true })
        {
            if (settleAbort && (!shared || !cancel)) continue;
            using var cancellation = new CancellationTokenSource();
            var body = new OwnedBody(Wire(ToolChunk)) { FailCleanup = failCleanup };
            void Callback() { if (cancel) cancellation.Cancel(); else throw new IOException(PrivateText); }
            var hooks = seam == "settlement" ?
                new GoogleGenerativeAIHooks { OnNativeSettlement = _ => Callback() } :
                new GoogleGenerativeAIHooks { OnEventPublished = value => { if (value is StreamTerminalEvent) Callback(); } };
            using var handler = new Handler((_, _) => Task.FromResult(Response(body)));
            using var client = new HttpClient(handler);
            var transport = new GoogleGenerativeAIHttpTransport(client, Model, Options() with { Hooks = hooks });
            StreamTerminalEvent terminal; ChatResult? result = null;
            if (shared)
            {
                var chatClient = new ChatClient(transport, 1);
                await using var run = settleAbort ?
                    await chatClient.StartWithAbortSettlementAsync(Request(), cancellation.Token) :
                    await chatClient.StartAsync(Request(), cancellation.Token);
                terminal = await Drain(run.ReadEventsAsync()); result = await run.Completion;
            }
            else terminal = await Drain(transport.StreamAsync(Request(), cancellation.Token));
            AssertTerminal(terminal, cancel ? NativeChatFailureCode.Cancelled : NativeChatFailureCode.SourceFailed,
                failCleanup, result, cancel ? StopReason.Aborted : StopReason.Error);
            Equal(shared && cancel && !settleAbort ? 0L : 17L, terminal.Message.Usage.TotalTokens);
            Check(body.AsyncDisposed, "Callback ran before physical cleanup.");
        }
    }

    private static async Task SharedFallback()
    {
        var errors = new (Exception Error, NativeChatFailureCode Code)[] {
            (new GoogleGenerativeAIException(GoogleFailure.Configuration, PrivateText), NativeChatFailureCode.UnsupportedFeature),
            (new GoogleGenerativeAIException(GoogleFailure.MissingKey, PrivateText), NativeChatFailureCode.UnsupportedFeature),
            (new GoogleGenerativeAIException(GoogleFailure.UnsupportedValue, PrivateText), NativeChatFailureCode.UnsupportedFeature),
            (new GoogleGenerativeAIException(GoogleFailure.MalformedStream, PrivateText), NativeChatFailureCode.MalformedStream),
            (new GoogleGenerativeAIException(GoogleFailure.UnexpectedEof, PrivateText), NativeChatFailureCode.UnexpectedEof),
            (new GoogleGenerativeAIException(GoogleFailure.ResourceLimit, PrivateText), NativeChatFailureCode.ResourceLimit),
            (new GoogleGenerativeAIException(GoogleFailure.ProviderError, PrivateText), NativeChatFailureCode.ProviderError),
            (new GoogleGenerativeAIException(GoogleFailure.CleanupFailed, PrivateText), NativeChatFailureCode.CleanupFailed),
            (new GoogleGenerativeAIException(GoogleFailure.SourceFailed, PrivateText), NativeChatFailureCode.SourceFailed),
            (new JsonException(PrivateText), NativeChatFailureCode.MalformedStream),
            (new StreamProtocolException(PrivateText), NativeChatFailureCode.MalformedStream),
            (new StreamLimitException(PrivateText), NativeChatFailureCode.ResourceLimit),
            (new IOException(PrivateText), NativeChatFailureCode.SourceFailed),
            (new OperationCanceledException(PrivateText), NativeChatFailureCode.SourceFailed)
        };
        foreach (var (error, code) in errors)
        foreach (var cancel in new[] { false, true })
        {
            var transport = new SubstituteTransport { Error = error, NoTerminal = true, HoldCleanup = true };
            await using var run = await new ChatClient(transport, 1).StartAsync(Request());
            var original = Drain(run.ReadEventsAsync());
            try
            {
                await transport.CleanupEntered.Task.WaitAsync(Deadline);
                Check(!original.IsCompleted && !run.Completion.IsCompleted, "Fallback failure skipped original cleanup.");
                if (cancel) run.Cancel();
                Check(!run.Completion.IsCompleted, "Fallback local abort detached cleanup.");
                transport.ReleaseCleanup.TrySetResult();
                AssertTerminal(await original, cancel ? NativeChatFailureCode.Cancelled : code, false,
                    await run.Completion, cancel ? StopReason.Aborted : StopReason.Error);
            }
            finally { transport.ReleaseCleanup.TrySetResult(); await Join(original); }
        }
        var eof = new SubstituteTransport { NoTerminal = true };
        await using (var run = await new ChatClient(eof, 1).StartAsync(Request()))
            AssertTerminal(await Drain(run.ReadEventsAsync()), NativeChatFailureCode.UnexpectedEof, false, await run.Completion);
        var invalid = new[] {
            new NativeChatDiagnostic((NativeChatAdapter)0, NativeChatFailureCode.ProviderError),
            new NativeChatDiagnostic((NativeChatAdapter)999, NativeChatFailureCode.ProviderError),
            new NativeChatDiagnostic(NativeChatAdapter.GoogleGenerativeAI, (NativeChatFailureCode)0),
            new NativeChatDiagnostic(NativeChatAdapter.GoogleGenerativeAI, (NativeChatFailureCode)999),
            new NativeChatDiagnostic(NativeChatAdapter.PiMessages, NativeChatFailureCode.ProviderError),
            new NativeChatDiagnostic(NativeChatAdapter.OpenAICompletions, NativeChatFailureCode.ProviderError)
        };
        foreach (var diagnostic in invalid)
        {
            var transport = new SubstituteTransport { TerminalDiagnostic = diagnostic, ErrorTerminal = true };
            await using var run = await new ChatClient(transport, 1).StartAsync(Request());
            AssertTerminal(await Drain(run.ReadEventsAsync()), NativeChatFailureCode.MalformedStream, false, await run.Completion);
        }
    }

    private static async Task PostTerminalCleanup()
    {
        foreach (var primary in new[] { "stop", "tool", "error" })
        foreach (var fail in new[] { false, true })
        foreach (var cancel in new[] { false, true })
        {
            var transport = new SubstituteTransport { Tool = primary != "stop", ErrorTerminal = primary == "error",
                HoldCleanup = true, FailCleanup = fail, ThrowCancellationCallback = cancel };
            await using var run = await new ChatClient(transport, 1).StartAsync(Request());
            var original = Drain(run.ReadEventsAsync());
            try
            {
                await transport.CleanupEntered.Task.WaitAsync(Deadline);
                Check(!run.Completion.IsCompleted && !original.IsCompleted, "Logical terminal detached cleanup.");
                if (cancel) run.Cancel();
                Check(!run.Completion.IsCompleted, "Abort settled before original iterator disposal.");
                transport.ReleaseCleanup.TrySetResult(); var terminal = await original; var result = await run.Completion;
                NativeChatFailureCode? expected = cancel ? NativeChatFailureCode.Cancelled :
                    primary == "error" ? NativeChatFailureCode.ProviderError : fail ? NativeChatFailureCode.CleanupFailed : null;
                AssertTerminal(terminal, expected, fail || cancel, result, cancel ? StopReason.Aborted : expected is null ?
                    primary == "tool" ? StopReason.ToolUse : StopReason.Stop : StopReason.Error);
                if (primary != "stop") Equal("owned-call", terminal.Message.Content.OfType<ToolCallContent>().Single().Id);
                if (primary == "error" && !cancel)
                    Equal("Authored provider primary.", terminal.Message.ExtraProperties!.Values["errorMessage"].Value.GetString());
                if (cancel) Equal(Diagnostic(NativeChatFailureCode.CleanupFailed), run.CleanupFailure!.NativeDiagnostic);
                Check(transport.Disposed, "Original iterator disposal did not settle.");
            }
            finally { transport.ReleaseCleanup.TrySetResult(); await Join(original); }
        }
    }

    private static async Task AgentAuthority()
    {
        foreach (var scenario in new[] { "provider", "http", "malformed", "eof", "resource", "unsupported", "callback", "cleanup", "cancel", "tool", "length" })
        {
            var wire = scenario switch {
                "provider" => Wire(ToolChunk.Replace("\"STOP\"", "\"SAFETY\"", StringComparison.Ordinal)),
                "malformed" => Wire(ToolChunk) + "data: {bad}\n\n",
                "eof" => Wire(ToolChunk.Replace(",\"finishReason\":\"STOP\"", "", StringComparison.Ordinal)),
                "unsupported" => Wire(ToolChunk.Replace("\"promptTokenCount\":11", "\"promptTokenCount\":0.5", StringComparison.Ordinal)),
                "length" => Wire(ToolChunk.Replace("\"STOP\"", "\"MAX_TOKENS\"", StringComparison.Ordinal)), _ => Wire(ToolChunk) };
            if (scenario == "http") wire = PrivateText;
            var body = new OwnedBody(wire) { HoldCleanup = true, FailCleanup = scenario is "cleanup" or "cancel" };
            var options = scenario == "callback" ? Options() with { Hooks = new() { OnProviderStreamEvent = (_, _, _) => throw new IOException(PrivateText) } } : Options();
            if (scenario == "resource") options = options with { MaximumContentCharacters = 1 };
            var sends = 0; var executor = new Executor(); StreamTerminalEvent? observed = null;
            using var handler = new Handler((_, _) => { sends++; return Task.FromResult(Response(body,
                scenario == "http" ? HttpStatusCode.BadRequest : HttpStatusCode.OK)); });
            using var client = new HttpClient(handler);
            await using var agent = new NativeAgent(new(Model, new GoogleGenerativeAIHttpTransport(client, Model, options),
                [new("inspect", executor)], Hooks: new(FinishTurnDecision: (_, _) => ValueTask.FromResult(AgentLoopFinishAction.End))),
                () => 123, new Sink((value, _) => { if (value is TurnStreamObserved { Event: StreamTerminalEvent terminal }) observed = terminal; return ValueTask.CompletedTask; }),
                new(StreamCapacity: 1));
            Task<AgentLoopResult>? original = null;
            try
            {
                original = agent.PromptAsync(Inputs()); await body.CleanupEntered.Task.WaitAsync(Deadline);
                Check(!original.IsCompleted && observed is null && executor.Executions == 0, "Agent gained authority before cleanup.");
                if (scenario == "cancel") agent.Abort();
                Check(!original.IsCompleted && executor.Executions == 0, "Agent cancellation detached cleanup.");
                body.ReleaseCleanup.TrySetResult(); var result = await original; var chat = result.Turns.Single().Result.Chat;
                NativeChatFailureCode? expected = scenario switch {
                    "provider" or "http" => NativeChatFailureCode.ProviderError, "malformed" => NativeChatFailureCode.MalformedStream,
                    "resource" => NativeChatFailureCode.ResourceLimit,
                    "eof" => NativeChatFailureCode.UnexpectedEof, "unsupported" => NativeChatFailureCode.UnsupportedFeature,
                    "callback" => NativeChatFailureCode.SourceFailed, "cleanup" => NativeChatFailureCode.CleanupFailed,
                    "cancel" => NativeChatFailureCode.Cancelled, _ => null };
                var terminal = observed ?? throw new InvalidOperationException("Agent omitted terminal observation.");
                // The Agent stamps thinkingLevel on its final message; native diagnostics
                // must still agree across the observed terminal and the actual chat result.
                Equal(expected is { } code ? Diagnostic(code) : null, chat.NativeDiagnostic);
                Equal(terminal.NativeDiagnostic, chat.NativeDiagnostic);
                Equal(terminal.NativeCleanupDiagnostic, chat.NativeCleanupDiagnostic);
                Equal(chat.NativeDiagnostic, chat.Failure?.NativeDiagnostic);
                Check((expected is null) == (chat.Failure is null), "Agent failure disagreement.");
                if (scenario == "cancel") Equal(ChatFailureKind.Cancelled, chat.Failure!.Kind);
                AssertTerminal(terminal, expected, scenario is "cleanup" or "cancel");
                Equal(scenario == "tool" ? 1 : 0, executor.Executions); Equal(1, sends);
                if (scenario == "length")
                    Equal(ToolFailureKind.Truncated, result.Turns.Single().Result.Tools.Outcomes.Single().Result.Failure!.Kind);
                Check(body.AsyncDisposed && !handler.Disposed && !agent.Snapshot.IsRunning, "Agent ownership remained active.");
            }
            finally { body.ReleaseCleanup.TrySetResult(); agent.Abort(); if (original is not null) await Join(original); await agent.WaitForIdleAsync(); }
        }
        // A substituted producer's successful tool terminal also loses authority if its
        // physical disposal subsequently fails in the shared run.
        var substitute = new SubstituteTransport { Tool = true, HoldCleanup = true, FailCleanup = true };
        var substituteExecutor = new Executor(); StreamTerminalEvent? substituteTerminal = null;
        await using var substituteAgent = new NativeAgent(new(Model, substitute, [new("inspect", substituteExecutor)],
            Hooks: new(FinishTurnDecision: (_, _) => ValueTask.FromResult(AgentLoopFinishAction.End))), () => 123,
            new Sink((value, _) => { if (value is TurnStreamObserved { Event: StreamTerminalEvent terminal }) substituteTerminal = terminal; return ValueTask.CompletedTask; }));
        Task<AgentLoopResult>? substituted = null;
        try
        {
            substituted = substituteAgent.PromptAsync(Inputs()); await substitute.CleanupEntered.Task.WaitAsync(Deadline);
            Check(!substituted.IsCompleted && substituteExecutor.Executions == 0, "Fallback Agent detached cleanup.");
            substitute.ReleaseCleanup.TrySetResult(); var chat = (await substituted).Turns.Single().Result.Chat;
            AssertTerminal(substituteTerminal!, NativeChatFailureCode.CleanupFailed, true);
            Equal(Diagnostic(NativeChatFailureCode.CleanupFailed), chat.NativeDiagnostic);
            Equal(chat.NativeDiagnostic, chat.Failure!.NativeDiagnostic); Equal(0, substituteExecutor.Executions);
        }
        finally { substitute.ReleaseCleanup.TrySetResult(); substituteAgent.Abort(); if (substituted is not null) await Join(substituted); await substituteAgent.WaitForIdleAsync(); }
    }

    private static async Task ApiAndWireControls()
    {
        Equal(1, (int)NativeChatAdapter.OpenAICompletions); Equal(2, (int)NativeChatAdapter.PiMessages);
        Equal(3, (int)NativeChatAdapter.GoogleGenerativeAI);
        Equal(8, Enum.GetValues<NativeChatFailureCode>().Length);
        foreach (var api in new[] { "google-generative-ai", "Google-generative-ai", "google-generative-ai-extra", "unknown", "pi-messages", "openai-completions" })
        {
            var request = Request() with { Model = Model with { Api = api } };
            var transport = new SubstituteTransport { NoTerminal = true, Error = new GoogleGenerativeAIException(GoogleFailure.ProviderError, PrivateText) };
            await using var run = await new ChatClient(transport, 1).StartAsync(request);
            var terminal = await Drain(run.ReadEventsAsync()); var result = await run.Completion;
            NativeChatDiagnostic? expected = api == "google-generative-ai" ? Diagnostic(NativeChatFailureCode.ProviderError) :
                api == "pi-messages" ? new(NativeChatAdapter.PiMessages, NativeChatFailureCode.SourceFailed) : null;
            var failure = result.Failure ?? throw new InvalidOperationException("Missing foreign fallback failure.");
            Equal(expected, terminal.NativeDiagnostic); Equal(expected, result.NativeDiagnostic); Equal(expected, failure.NativeDiagnostic);
            Check(!failure.Message.Contains(PrivateText, StringComparison.Ordinal), "Typed foreign fallback leaked private text.");
        }
        foreach (var api in new[] { "pi-messages", "openai-completions", "unknown" })
        {
            var request = Request() with { Model = Model with { Api = api } };
            var transport = new SubstituteTransport { FailCleanup = true };
            await using var run = await new ChatClient(transport, 1).StartAsync(request);
            var terminal = await Drain(run.ReadEventsAsync()); var result = await run.Completion;
            Check(terminal is StreamDone && result.Failure is null && result.NativeDiagnostic is null, "Existing non-Google cleanup settlement changed.");
            NativeChatDiagnostic? expected = api == "pi-messages" ? new NativeChatDiagnostic(NativeChatAdapter.PiMessages, NativeChatFailureCode.CleanupFailed) :
                api == "openai-completions" ? new(NativeChatAdapter.OpenAICompletions, NativeChatFailureCode.CleanupFailed) : null;
            Equal(expected, terminal.NativeCleanupDiagnostic); Equal(expected, result.NativeCleanupDiagnostic);
        }
        using var preaborted = new CancellationTokenSource(); preaborted.Cancel();
        var unused = new SubstituteTransport();
        await using (var run = await new ChatClient(unused, 1).StartAsync(Request(), preaborted.Token))
        {
            AssertTerminal(await Drain(run.ReadEventsAsync()), NativeChatFailureCode.Cancelled, false, await run.Completion, StopReason.Aborted);
            Equal(0, unused.Invocations);
        }
        foreach (var invalid in new[] { new NativeChatDiagnostic((NativeChatAdapter)0, NativeChatFailureCode.ProviderError),
            new NativeChatDiagnostic(NativeChatAdapter.GoogleGenerativeAI, (NativeChatFailureCode)0) })
        {
            var transport = new SubstituteTransport { CleanupDiagnostic = invalid };
            await using var run = await new ChatClient(transport, 1).StartAsync(Request());
            AssertTerminal(await Drain(run.ReadEventsAsync()), NativeChatFailureCode.MalformedStream, false, await run.Completion);
        }
    }

    private sealed class SubstituteTransport : IChatTransport
    {
        internal bool Tool, ErrorTerminal, NoTerminal, HoldCleanup, FailCleanup, ThrowCancellationCallback, Disposed;
        internal int Invocations;
        internal Exception? Error;
        internal NativeChatDiagnostic? TerminalDiagnostic, CleanupDiagnostic;
        internal readonly TaskCompletionSource CleanupEntered = Gate(), ReleaseCleanup = Gate();
        public async IAsyncEnumerable<StreamEvent> StreamAsync(ChatRequest request, [EnumeratorCancellation] CancellationToken token = default)
        {
            Invocations++;
            using var registration = ThrowCancellationCallback ? token.Register(() => throw new IOException(PrivateText)) : default;
            try
            {
                var partial = new AssistantMessage(request.Model.Api, request.Model.Provider, request.Model.Id, request.Timestamp, [], TokenUsage.Zero, StopReason.Pending);
                yield return new StreamStarted(partial);
                if (Error is not null) throw Error;
                if (NoTerminal) yield break;
                var call = new ToolCallContent("owned-call", "inspect", JsonData.Parse("""{"value":7,"keep":null}"""));
                if (Tool)
                {
                    yield return new ToolCallStarted(0, call with { Arguments = JsonData.EmptyObject });
                    yield return new ToolCallDelta(0, """{"value":7,"keep":null}""");
                    yield return new ToolCallEnded(0, call);
                }
                var reason = ErrorTerminal ? StopReason.Error : Tool ? StopReason.ToolUse : StopReason.Stop;
                var final = partial with { Content = Tool ? [call] : [], StopReason = reason,
                    ExtraProperties = ErrorTerminal ? JsonFields.Empty.Set("errorMessage", JsonData.Parse("\"Authored provider primary.\"")) : null };
                if (ErrorTerminal)
                    yield return new StreamError(reason, final) { NativeDiagnostic = TerminalDiagnostic ?? Diagnostic(NativeChatFailureCode.ProviderError), NativeCleanupDiagnostic = CleanupDiagnostic };
                else yield return new StreamDone(reason, final) { NativeDiagnostic = TerminalDiagnostic, NativeCleanupDiagnostic = CleanupDiagnostic };
            }
            finally
            {
                CleanupEntered.TrySetResult(); if (HoldCleanup) await ReleaseCleanup.Task;
                Disposed = true; if (FailCleanup) throw new IOException(PrivateText);
            }
        }
    }
    private sealed class Handler(Func<HttpRequestMessage, CancellationToken, Task<HttpResponseMessage>> send) : HttpMessageHandler
    {
        internal bool Disposed;
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken token) => send(request, token);
        protected override void Dispose(bool disposing) { Disposed = true; base.Dispose(disposing); }
    }
    private static HttpResponseMessage Response(OwnedBody body, HttpStatusCode status = HttpStatusCode.OK) =>
        new(status) { Content = new BodyContent(body) };
    private sealed class BodyContent(OwnedBody body) : HttpContent
    {
        protected override Task SerializeToStreamAsync(Stream stream, TransportContext? context) => throw new NotSupportedException();
        protected override bool TryComputeLength(out long length) { length = 0; return false; }
        protected override Task<Stream> CreateContentReadStreamAsync() => Task.FromResult<Stream>(body);
        protected override Task<Stream> CreateContentReadStreamAsync(CancellationToken token) => Task.FromResult<Stream>(body);
        protected override void Dispose(bool disposing) { body.Dispose(); base.Dispose(disposing); }
    }
    private sealed class OwnedBody(string wire) : Stream
    {
        private readonly byte[] _bytes = Encoding.UTF8.GetBytes(wire); private int _offset; private bool _readHeld;
        internal bool FailRead, HoldCleanup, FailCleanup, FailSyncCleanup, AsyncDisposed, SyncDisposed;
        internal TaskCompletionSource? ReadEntered, ReleaseRead;
        internal readonly TaskCompletionSource CleanupEntered = Gate(), ReleaseCleanup = Gate();
        public override bool CanRead => true;
        public override bool CanSeek => false;
        public override bool CanWrite => false;
        public override long Length => _bytes.Length;
        public override long Position { get => _offset; set => throw new NotSupportedException(); }
        public override async ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken token = default)
        {
            if (!_readHeld && ReadEntered is not null) { _readHeld = true; ReadEntered.TrySetResult(); await ReleaseRead!.Task; }
            if (FailRead) throw new IOException(PrivateText);
            var count = Math.Min(buffer.Length, _bytes.Length - _offset); _bytes.AsMemory(_offset, count).CopyTo(buffer); _offset += count; return count;
        }
        public override async ValueTask DisposeAsync()
        {
            CleanupEntered.TrySetResult(); if (HoldCleanup) await ReleaseCleanup.Task;
            AsyncDisposed = true; if (FailCleanup) throw new IOException(PrivateText);
        }
        protected override void Dispose(bool disposing)
        {
            SyncDisposed = true; base.Dispose(disposing);
            if (FailSyncCleanup) throw new IOException(PrivateText);
        }
        public override int Read(byte[] buffer, int offset, int count) => throw new NotSupportedException();
        public override void Flush() => throw new NotSupportedException();
        public override long Seek(long offset, SeekOrigin origin) => throw new NotSupportedException();
        public override void SetLength(long value) => throw new NotSupportedException();
        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();
    }
    private sealed class Sink(Func<AgentEvent, CancellationToken, ValueTask> emit) : IAgentEventSink
    { public ValueTask EmitAsync(AgentEvent observation, CancellationToken token) => emit(observation, token); }
    private sealed class Executor : IToolExecutor
    {
        internal int Executions;
        public ValueTask<ToolResult> ExecuteAsync(ToolInvocation invocation, CancellationToken token)
        { Executions++; return ValueTask.FromResult(ToolResult.Success("authored")); }
    }
}
