// Root-run pure/read-only profile probes; no compiler/API, child process, source runtime or capture.
import assert from 'node:assert/strict';
import { EventEmitter } from 'node:events';
import { join, resolve } from 'node:path';
import { readPlan, assertProfilePlan, readBaseline, classifyPackageTarget, assertRequiredPublishedBlockers, readPublishedArtifacts, mandatoryLockInventory, parseArgs, snapshot, diagnosticMethods, assertOriginalRoots, verifyOracle, profileFiles } from './full-structural-openai-common.mjs';
import { nativeArguments, assertNativeSpawn, runtimeModuleRows, observeOwnedChildClose, awaitExit } from './full-structural-openai-preload.mjs';
import { childArgs, assertFrozen, observeDriverChild, assertPhysicalNativeClose } from './run-full-structural-openai.mjs';
import { hash, regular, repo } from './full-structural-openai-common.mjs';
import { readCurrentBaseline, currentBaselineCensus, assertCurrentBaselineCensus, assertRetainedObservation, parsePublicAstSchema } from './full-structural-openai-common.mjs';
import { createStructuralInventory, StructuralBudgetError, requiredCheckerOperations, unavailablePublicFields, finishNativeSession, persistCaptureArtifacts, isRetainedSymbolTypePanic, retainStructuralFailure } from './full-structural-openai-driver.mjs';
import { createEncodingBudget, streamingJsonChunks, writeStreamedEvidence, writeProvenanceBundle, verifyProvenanceBundle, verifyStreamedFile, verifyProtocolEvidence, failureIdentity, textIdentity, captureEvidenceFailures } from './full-structural-openai-common.mjs';
const plan = readPlan(), cases = [];
function test(name, action) { try { action(); cases.push({ name, passed: true }); } catch (error) { cases.push({ name, passed: false, error: { name: error.name, message: error.message } }); } }
function reject(name, action) { test(name, () => assert.throws(action)); }
const sourcePaths = ['packages/ai/src/index.ts', 'packages/example/src/a.ts'], baseline = readBaseline(plan), artifacts = await readPublishedArtifacts(plan);
const base = { manifestPath: 'packages/example/package.json', package: 'example', field: 'main', subpath: '.', conditions: [], target: 'dist/index.js' };
test('bare main path is classified but never mapped to src', () => { const x = classifyPackageTarget(base, sourcePaths); assert.equal(x.canonicalTarget, 'packages/example/dist/index.js'); assert.equal(x.canonicalTargetPresent, false); assert.equal(x.publishedTarget.state, 'metadata-not-acquired'); assert.equal(x.mandatoryMappingOrOwnershipBlocker, true); assert.equal(x.inferredDistToSourceMapping, false); });
test('dot-prefixed main has exact package-relative membership', () => { const x = classifyPackageTarget({ ...base, target: './src/a.ts' }, sourcePaths); assert.equal(x.canonicalTargetPresent, true); assert.deepEqual(x.matchingSourceTargets, ['packages/example/src/a.ts']); assert.equal(x.sourceOwnershipVerified, false); });
for (const field of ['bin','source','types','typings']) test('bare ' + field + ' classified independently from exports', () => assert.equal(classifyPackageTarget({ ...base, field, target: 'src/a.ts' }, sourcePaths).canonicalTargetPresent, true));
test('exports bare relative cannot become a valid mapping', () => { const row = classifyPackageTarget({ ...base, field: 'exports' }, sourcePaths); assert.equal(row.targetSyntax, 'invalid-exports-relative-target'); assert.equal(row.mandatoryMappingOrOwnershipBlocker, true); });
test('exports dot-relative exact literal is retained', () => assert.equal(classifyPackageTarget({ ...base, field: 'exports', target: './src/a.ts' }, sourcePaths).canonicalTargetPresent, true));
for (const target of ['../outside.ts','/absolute.ts','C:/drive.ts','a:stream','a\\b','https://example.invalid/a','%2e%2e/a','a//b','a/./b','a.','con.txt','a?b','a**b']) test('unsafe or unsupported target stays explicit: ' + target, () => { const x = classifyPackageTarget({ ...base, target }, sourcePaths); assert.equal(x.mandatoryMappingOrOwnershipBlocker, true); assert.equal(x.publishedTarget.state, 'unresolved-target-syntax'); assert.equal(x.inferredDistToSourceMapping, false); assert.equal(x.target, target); });
for (const target of [null, [], {}, 1, false]) test('non-string/null target preserved: ' + JSON.stringify(target), () => { const x = classifyPackageTarget({ ...base, target }, sourcePaths); assert.deepEqual(x.target, target); assert.equal(x.mandatoryMappingOrOwnershipBlocker, true); assert.equal(x.canonicalTargetPresent, undefined); });
test('explicit null export denial remains distinct', () => assert.equal(classifyPackageTarget({ ...base, field: 'exports', target: null }, sourcePaths).targetSyntax, 'explicit-null-export-denial'));
test('raw condition order and target are not mutated', () => { const row = { ...base, conditions: ['node','import',1], target: './src/*.ts' }, before = JSON.stringify(row), x = classifyPackageTarget(row, sourcePaths); assert.equal(JSON.stringify(row), before); assert.equal(x.conditions, row.conditions); assert.equal(x.wildcard, true); assert.deepEqual(x.matchingSourceTargets, ['packages/example/src/a.ts']); });
test('acquired member absence differs from missing archive', () => { const acquired = { archive: { sha256: 'A' }, files: [{ path: 'other', bytes: 1, sha256: 'B' }] }, a = classifyPackageTarget(base, sourcePaths, acquired), b = classifyPackageTarget(base, sourcePaths, { registry: { name: 'example' } }); assert.equal(a.publishedTarget.state, 'acquired-member-absent'); assert.equal(b.publishedTarget.state, 'artifact-not-acquired'); });
test('actual complete813-file pi-ai package evidence', () => { const ai = artifacts.find(row => row.name === '@earendil-works/pi-ai'); assert.equal(ai.files.length, 813); const cli = ai.files.find(row => row.path === 'dist/cli.js'); assert.equal(cli.bytes, 4762); assert.equal(cli.sha256, '15efe3d849331391ced3f38e55f53609a7952e8359229c8b65c1172e8e9608a5'); assert.equal(ai.packageRuntimeExecuted, false); });
const required = plan.requiredPublishedOwnershipBlockers.map(required => { const row = baseline.entrypoints.find(row => row.manifestPath === required.manifestPath && row.field === required.field && row.subpath === required.subpath && row.target === required.target); assert(row); return { ...row, ...classifyPackageTarget(row, sourcePaths, artifacts.find(item => item.name === row.package)) }; });
test('all three actual public main/bin targets remain mandatory ownership blockers', () => { assertRequiredPublishedBlockers(required, plan); assert.equal(required[0].publishedTarget.state, 'acquired-member-present'); assert.equal(required[1].publishedTarget.state, 'artifact-not-acquired'); assert.equal(required[2].publishedTarget.state, 'artifact-not-acquired'); });
reject('omitting one required public target is rejected', () => assertRequiredPublishedBlockers(required.slice(1), plan));
reject('unknown ownership cannot be silently resolved', () => assertRequiredPublishedBlockers(required.map((row, i) => i ? row : { ...row, mandatoryMappingOrOwnershipBlocker: false }), plan));
test('complete released-catalog family/root/public baseline preserved', () => { assert.deepEqual(Object.keys(baseline.diagnostics), diagnosticMethods); assert.equal(baseline.diagnostics.getSemanticDiagnostics.length, 1246); assert.equal(baseline.unresolved.length, 711); assert.equal(baseline.rootFiles.length, 1661); assert.equal(baseline.entrypoints.length, 150); assert(baseline.rootFiles.every(path => baseline.sourceFiles.includes(path))); const rows = mandatoryLockInventory(baseline, plan); assert.equal(rows.length, 34); assert.equal(rows.reduce((n, row) => n + row.parsedSpecifiers.length, 0), 43); });
test('snapshot preserves explicit null/absent/opaque/ordered arrays', () => { const value = { opaque: { a: [2,1], z: null }, present: null }; assert.deepEqual(snapshot(value, plan.limits, 'probe'), value); assert.equal(Object.hasOwn(snapshot(value, plan.limits, 'probe'), 'missing'), false); });
const scratch = resolve(plan.oracle, '..', 'Pi-openai-pure-probe-never-created');
test('explicit disjoint scratch accepted read-only', () => assert.equal(parseArgs(['--check','--oracle',plan.oracle,'--scratch',scratch], plan).mode, '--check'));
test('run-root forwards the exact oracle and every physical output root', () => { const value = parseArgs(['--check','--oracle',plan.oracle,'--run-root',scratch], plan); assert.equal(value.oracle, resolve(plan.oracle)); assert.equal(value.runRoot, scratch); assert.equal(value.scratch, scratch); assert.deepEqual(value, parseArgs(['--check','--oracle',plan.oracle,'--scratch',scratch], plan)); });
reject('run-root and scratch conflict before any IO writes', () => parseArgs(['--check','--run-root',scratch,'--scratch',scratch], plan));
reject('missing run-root value rejected', () => parseArgs(['--check','--run-root'], plan));
reject('duplicate run-root rejected', () => parseArgs(['--check','--run-root',scratch,'--run-root',scratch], plan));
test('source-relative validation preserves every original root without changing raw output', () => { const oldRoot = join(plan.origin.root, 'upstream'), newRoot = join(plan.oracle, 'upstream'), before = [join(newRoot, 'packages/a.ts')]; assert.equal(assertOriginalRoots(before, [join(oldRoot, 'packages/a.ts')], newRoot, oldRoot).allOriginalRootsPresent, true); assert.deepEqual(before, [join(newRoot, 'packages/a.ts')]); });
reject('omitted original root is rejected', () => assertOriginalRoots([], [join(plan.origin.root, 'upstream/packages/a.ts')], join(plan.oracle, 'upstream'), join(plan.origin.root, 'upstream')));
for (const args of [[],['--check','--scratch'],['--check','--capture-new','--scratch',scratch],['--unknown','--scratch',scratch],['--check','--scratch',plan.origin.root]]) reject('strict profile args ' + JSON.stringify(args), () => parseArgs(args, plan));
test('Windows preload argv uses file URL', () => { const args = childArgs(); assert.equal(args[0], '--import'); assert(args[1].startsWith('file:///')); assert(args[1].endsWith('/full-structural-openai-preload.mjs')); });
const context = { count: 0, exe: join(plan.oracle, plan.native.path), oracle: plan.oracle, scratch, cwd: scratch, hash: plan.native.sha256, expectedHash: plan.native.sha256 }, options = { stdio: ['pipe','pipe','inherit'] };
test('exact native spawn shape qualified without execution', () => assertNativeSpawn(context.exe, nativeArguments(plan.oracle), options, context));
for (const [label, mutate] of [['second process', x => x.count++],['bad executable hash', x => x.hash = '0'.repeat(64)],['wrong scratch cwd', x => x.cwd = plan.oracle]]) reject(label + ' denied', () => { const x = { ...context }; mutate(x); assertNativeSpawn(x.exe, nativeArguments(plan.oracle), options, x); });
reject('native wrong argv denied', () => assertNativeSpawn(context.exe, ['--version'], options, context));
reject('native inherited env override denied', () => assertNativeSpawn(context.exe, nativeArguments(plan.oracle), { ...options, env: {} }, context));
reject('native shell launch denied', () => assertNativeSpawn(context.exe, nativeArguments(plan.oracle), { ...options, shell: true }, context));
test('runtime loading excludes all upstream/catalog/SDK source/JS/declaration data', () => { const rows = runtimeModuleRows({ files: [{ path: 'upstream/packages/ai/src/providers/data/openai.json' }, { path: 'upstream/node_modules/typebox/index.mjs' }, { path: 'upstream/packages/ai/node_modules/openai/index.mjs' }, { path: 'upstream/packages/ai/node_modules/openai/index.d.mts' }, { path: 'upstream/packages/ai/node_modules/openai/src/internal/auth/x509-transport-state.cts' }, { path: 'node_modules/typescript/dist/api/async/api.js' }] }, plan); assert.deepEqual(rows, [{ path: 'node_modules/typescript/dist/api/async/api.js' }]); });
test('new profile binds actual 8129-payload root receipt and all retained declarations', () => { assertProfilePlan(plan); assert.equal(plan.receipt.sha256, '1e7f61d543738e4c7ad81df5cacdf98c8d75190633f881fd3741a127c6d8a577'); assert.equal(plan.receipt.payloadFiles, 8129); assert.equal(plan.receipt.allAddedPackageFiles, 5463); assert.equal(plan.receipt.allAdmittedDeclarations, 1712); assert.equal(profileFiles.length, 7); });
for (const [label, mutate] of [
  ['partial VFS payload', p => { p.executionBoundary.vfsPayloadFiles = 4581; }],
  ['fake pending admission', p => { p.receipt.actualAdmissionPinPending = true; }],
  ['wrong actual receipt', p => { p.receipt.sha256 = '0'.repeat(64); }],
  ['omitted OpenAI declarations', p => { p.receipt.openaiDeclarations = 0; }],
  ['runtime SDK import', p => { p.executionBoundary.runtimeModulePrefix = 'upstream/packages/ai/node_modules/openai/'; }],
  ['missing diagnostic family', p => { p.diagnosticMethods.pop(); }],
  ['mandatory scope narrowed to remaining locks', p => { p.baseline.mandatoryNearestLockInstances = 26; }],
  ['optional peer exemption', p => { p.sdkDeclarationResolution.optionalPeersAreNotExemptions = false; }],
  ['#x509 source type condition omitted', p => { p.sdkDeclarationResolution.knownDeclarationImports.pop(); }],
  ['absent canonical peer requirement guessed away', p => { p.sdkDeclarationResolution.missingCanonicalPeerInstances.pop(); }],
  ['structural field census claimed exhaustive', p => { p.sdkDeclarationResolution.structuralTypeInventoryExhaustive = true; }],
  ['public closure from repeatability', p => { p.semanticPublicClosure = true; }],
]) reject('new profile rejects ' + label, () => { const p = JSON.parse(JSON.stringify(plan)); mutate(p); assertProfilePlan(p); });
const verified = await verifyOracle(plan.oracle, plan);
test('whole admitted oracle reverified read-only without compiler execution', () => { assert.equal(verified.receipt.files.length, 8129); assert.equal(verified.originalSourceRows.length, 2093); assert.equal(verified.catalogRows.length, 43); assert.equal(verified.addedFiles.length, 5463); assert.equal(verified.packages.length, 11); assert.equal(verified.sdkArtifact.archive.files.length, 3548); assert.equal(verified.sdkArtifact.declarationFiles, 784); assert.equal(verified.receipt.packageCodeImported, false); assert.equal(verified.receipt.compilerImported, false); assert.equal(verified.receipt.nativeExecuted, false); });
test('actual catalog and SDK artifacts stay separately attributed', () => { assert.equal(verified.sourceArtifact.catalogFiles.length, 43); assert.equal(verified.sourceArtifact.selectedPayloadBytes, 902551); assert.equal(verified.sdkArtifact.target, 'upstream/packages/ai/node_modules/openai'); assert.equal(verified.sdkArtifact.notices.length, 4); assert.equal(verified.sdkArtifact.sdkRuntimeExecuted, false); const keys = new Set(verified.sdkArtifact.archive.files.map(row => row.path)); assert(keys.has('resources/responses/responses.d.ts')); assert(keys.has('index.d.mts')); assert(keys.has('src/internal/auth/x509-transport-state.cts')); });
test('frozen expected/harness/receipt pins reject mutation', () => { const bytes = Buffer.from('{"observed":null}\n'), harness = [{ path: 'producer', sha256: 'H' }], manifest = { harness, receiptSha256: 'R', expected: { bytes: bytes.length, sha256: hash(bytes) } }; assertFrozen(manifest, bytes, harness, 'R'); assert.throws(() => assertFrozen(manifest, Buffer.from('{"observed":0}\n'), harness, 'R')); assert.throws(() => assertFrozen(manifest, bytes, [...harness,{path:'changed'}], 'R')); assert.throws(() => assertFrozen(manifest, bytes, harness, 'changed')); });
async function asyncTest(name, action) { try { await action(); cases.push({ name, passed: true }); } catch (error) { cases.push({ name, passed: false, error: { name: error.name, message: error.message } }); } }
const current = readCurrentBaseline(plan);
test('exact pinned current artifact contains 7393 exports and 7449 export declaration occurrences', () => {
  assert.equal(hash(regular(join(repo, plan.currentWholeBaseline.path), plan.limits.snapshotBytes)), plan.currentWholeBaseline.sha256);
  const exports = current.modules.flatMap(row => row.exports ?? []); assert.equal(exports.length, 7393); assert.equal(exports.flatMap(symbol => symbol.declarations).length, 7449); assert.equal(exports.filter(symbol => symbol.flags & 2097152).length, 2440); assert.equal(current.modules.filter(row => row.moduleSymbol).length, 742);
  assert.equal(current.modules.filter(row => row.moduleSymbol && row.exports.length === 0).length, 16); assert.equal(current.sourceFiles.length, 2773); assert.equal(current.programDeclarationFiles.length, 1065); assert.equal(current.declarationAdmission.declarationsConsumedInProgram.length, 993); assertCurrentBaselineCensus(current, plan.currentWholeBaseline);
});
test('initial inflated authored counts are rejected without changing the genuine artifact', () => {
  assert.throws(() => assertCurrentBaselineCensus(current, { ...plan.currentWholeBaseline, exportOccurrences: 7451 }), /Current census/); assert.throws(() => assertCurrentBaselineCensus(current, { ...plan.currentWholeBaseline, declarationHandleOccurrences: 7507 }), /Current census/);
});
for (const [field, count] of Object.entries(currentBaselineCensus(current))) if (typeof count === 'number') reject('every recorded current count is checked against the actual artifact: ' + field, () => assertCurrentBaselineCensus(current, { ...plan.currentWholeBaseline, [field]: count + 1 }));
test('every diagnostic-family count is checked in the recorded current census', () => { for (const method of diagnosticMethods) assert.throws(() => assertCurrentBaselineCensus(current, { ...plan.currentWholeBaseline, diagnosticCounts: { ...plan.currentWholeBaseline.diagnosticCounts, [method]: plan.currentWholeBaseline.diagnosticCounts[method] + 1 } })); });
test('same-count export omission and duplication still fails exact retained observation', () => {
  const modules = current.modules.map(row => ({ ...row, exports: row.exports?.slice() })), row = modules.find(module => module.exports?.filter(symbol => symbol.flags === 16 && symbol.declarations.length === 1 && symbol.valueDeclaration).length >= 2), functions = row.exports.map((symbol, index) => ({ symbol, index })).filter(item => item.symbol.flags === 16 && item.symbol.declarations.length === 1 && item.symbol.valueDeclaration); row.exports[functions[1].index] = row.exports[functions[0].index]; const changed = { ...current, modules };
  assert.deepEqual(currentBaselineCensus(changed), currentBaselineCensus(current)); assert.throws(() => assertRetainedObservation(changed, current), /Whole predecessor observation changed: modules/);
});
test('all original and current raw observation fields remain exact', () => { assertRetainedObservation({ ...current, kind: 'new', structuralTypeInventory: {} }, current); const changed = structuredClone(current); changed.diagnostics.getSemanticDiagnostics.pop(); assert.throws(() => assertRetainedObservation(changed, current)); });
test('the 2440 actual alias occurrences are retained before querying', () => assert.equal(current.modules.flatMap(row => row.exports ?? []).filter(symbol => symbol.flags & 2097152).length, 2440));
test('all 800 module and 150 public condition rows remain required', () => { assert.equal(current.modules.length, 800); assert.equal(current.entrypoints.length, 150); assert.equal(plan.structuralInventory.allModuleCandidates, 800); assert.equal(plan.structuralInventory.allEntrypointRows, 150); });
test('unsupported public native fields are explicit mandatory decisions', () => assert.deepEqual(plan.structuralInventory.unsupportedCheckerFields, unavailablePublicFields));
for (const [name, mutate] of [['hidden truncation', p => p.structuralInventory.budgetOverflow = 'truncate'],['pretty-string closure', p => p.structuralInventory.formatStringsAreStructuralTypes = true],['method presence substituted for execution', p => p.structuralInventory.methodPresenceIsExecution = true],['permanent unsupported exemption', p => p.structuralInventory.unsupportedArePermanentExemptions = true],['narrow module roots', p => p.structuralInventory.allModuleCandidates = 742],['narrow conditions', p => p.structuralInventory.allEntrypointRows = 27]]) reject('structural profile rejects ' + name, () => { const p = structuredClone(plan); mutate(p); assertProfilePlan(p); });

function graphFixture(offset = 0) {
  const baseFields = ['kind','pos','end','flags','parent'], astSchema = { kindFields: new Map([[1,[...baseFields,'typeParameters','questionToken','readonlyToken','modifiers','opaque']],[2,baseFields],[3,[...baseFields,'constraint','defaultType']]]), tokenKinds: new Set(), baseFields, arrayFields: ['pos','end','hasTrailingComma','transformFlags'] };
  const enums = { SymbolFlags: { Value: 1, Type: 2, Alias: 4 }, SignatureKind: { Call: 0, Construct: 1 }, ObjectFlags: { Mapped: 32 }, TypeFlags: { Freshable: 1024 }, astSchema }, project = { id: 'actual-mock-project' };
  const predicates = ['isClassOrInterface','isUnionType','isIntersectionType','isObjectType','isIntrinsicType','isErrorType','isLiteralType','isStringLiteralType','isNumberLiteralType','isBigIntLiteralType','isBooleanLiteralType','isTypeReference','isTupleType','isIndexType','isIndexedAccessType','isConditionalType','isSubstitutionType','isTemplateLiteralType','isStringMappingType','isTypeParameter'];
  class T { constructor(id, names = [], fields = {}) { this.id = offset + id; this.flags = 0; this.names = new Set(names); Object.assign(this, fields); } async getSymbol() { return this.symbol; } async getAliasSymbol() { return undefined; } async getAliasTypeArguments() { return this.aliasArguments ?? []; } async getTypes() { return this.parts ?? []; } async getTarget() { return this.target ?? this; } async getBaseTypes() { return []; } async getTypeParameters() { return this.parameters ?? []; } async getOuterTypeParameters() { return []; } async getLocalTypeParameters() { return this.parameters ?? []; } async getFreshType() { return this; } async getRegularType() { return this; } async getObjectType() { return this.objectTypeValue; } async getIndexType() { return this.indexTypeValue; } async getCheckType() { return this.checkTypeValue; } async getExtendsType() { return this.extendsTypeValue; } async getTrueType() { return this.trueTypeValue; } async getFalseType() { return this.falseTypeValue; } async getBaseType() { return this.baseTypeValue; } async getConstraint() { return this.constraintValue; } }
  for (const name of predicates) T.prototype[name] = function() { return this.names.has(name); };
  class S { constructor(id, name, flags, fields = {}) { Object.assign(this, { id: offset + id, name, escapedName: name, flags, checkFlags: 0, declarations: [] }, fields); } async getParent() { return undefined; } async getExportSymbol() { return this; } async getMembers() { return this.memberMap ?? new Map(); } async getExports() { return this.exportMap ?? new Map(); } }
  class N { constructor(kind, fields = {}) { Object.assign(this, { kind, pos: 1, end: 9, flags: 0 }, fields); } getSourceFile() { return { fileName: 'unchanged.ts' }; } getFullText() { return 'type X<T = string> = { readonly item?: T | null };'; } getText() { return this.getFullText(); } }
  class H { constructor() { this.path = 'c:/unchanged.ts'; this.index = 42; this.kind = 1; } async resolve() { return node; } }
  const primitive = new T(1, ['isIntrinsicType'], { intrinsicName: 'string' }), errorType = new T(2, ['isIntrinsicType','isErrorType'], { intrinsicName: 'error' }), union = new T(3, ['isUnionType'], { parts: [primitive,errorType] }), rootType = new T(4, ['isObjectType'], { objectFlags: 32 }), callable = new T(5, ['isObjectType'], { objectFlags: 0 }), parameterType = new T(6, ['isTypeParameter'], { isThisType: false }), sameDisplayDifferentIdentity = new T(7, ['isIntrinsicType'], { intrinsicName: 'string' }), literal = new T(8, ['isLiteralType','isBigIntLiteralType'], { flags: 1024, value: -123n });
  const child = new N(2), node = new N(1, { typeParameters: [new N(3, { defaultType: child, constraint: child })], questionToken: null, readonlyToken: { kind: 4 }, modifiers: [{ kind: 5 }], opaque: ['x','y'] });
  const root = new S(10, 'Root', 3, { valueType: rootType, declaredType: rootType, declarations: [new H()] }), alias = new S(11, 'Alias', 4, { alias: root }), unknown = new S(12, 'Missing', 4, { unknown: true }), property = new S(13, 'item', 1, { valueType: union }), method = new S(14, 'method', 1, { valueType: callable }), parameter = new S(15, 'arg', 1, { valueType: parameterType }), other = new S(16, 'distinct', 1, { valueType: sameDisplayDifferentIdentity }), bigint = new S(17, 'bigint', 1, { valueType: literal }); unknown.alias = unknown;
  rootType.properties = [property,method,other,bigint]; rootType.symbol = root; root.memberMap = new Map([['self',root]]); root.exportMap = new Map([['Alias',alias],['Missing',unknown]]); callable.symbol = method;
  const signature = { id: offset + 20, declaration: new H(), hasRestParameter: true, isConstruct: false, isAbstract: false, async getTarget() { return this; }, async getTypeParameters() { return [parameterType]; }, async getParameters() { return [parameter]; }, async getThisParameter() { return undefined; } }; callable.signatures = [signature];
  const checker = { async isUnknownSymbol(symbol) { return !!symbol.unknown; }, async getImmediateAliasedSymbol(symbol) { return symbol.alias; }, async getAliasedSymbol(symbol) { return symbol.alias; }, async getTypeOfSymbol(symbol) { return symbol.valueType; }, async getDeclaredTypeOfSymbol(symbol) { return symbol.declaredType; }, async getPropertiesOfType(type) { return type.properties ?? []; }, async getSignaturesOfType(type, kind) { return kind === 0 ? type.signatures ?? [] : []; }, async getReturnTypeOfSignature() { return rootType; }, async getRestTypeOfSignature() { return union; }, async getTypePredicateOfSignature() { return { kind: 1, parameterName: 'arg', parameterIndex: 0, type: primitive }; }, async getIndexInfosOfType(type) { return type === rootType ? [{ keyType: primitive, valueType: union, isReadonly: true, declaration: new H() }] : []; }, async getTypeArguments() { return []; }, async getConstraintOfTypeParameter() { return primitive; }, async getBaseConstraintOfType() { return undefined; }, async getParameterType() { return parameterType; }, async getTypeAtLocation() { return rootType; }, async getTypeFromTypeNode() { return primitive; }, async typeToString() { return 'same pretty string'; } };
  return { checker, project, enums, root, alias, unknown, node, child, limits: { symbols: 100, types: 100, signatures: 100, declarations: 100, syntaxNodes: 1000, syntaxDepth: 100, operations: 10000 } };
}
async function fixtureCapture(fixture) { const graph = createStructuralInventory(fixture.checker, fixture.project, fixture.enums, fixture.limits); graph.seedModule('unchanged.ts', fixture.root, [fixture.root,fixture.alias,fixture.unknown]); graph.seedModule('not-in-program.ts', undefined, []); graph.seedEntrypoints([{ manifestPath: 'package.json', field: 'exports', subpath: '.', conditions: ['node','import'], target: './unchanged.ts', canonicalTarget: 'unchanged.ts', matchingSourceTargets: ['unchanged.ts'], canonicalTargetPresent: true, sourceOwnershipVerified: false }]); return { graph, output: await graph.finish() }; }
await asyncTest('real identity cycles terminate without discarding symbol/type/signature edges', async () => { const { graph, output } = await fixtureCapture(graphFixture()); assert.equal(output.reachableGraphTraversalCompleted, true); assert.equal(output.moduleRoots.length, 2); assert.deepEqual(output.moduleRoots[1].moduleSymbol, { state: 'undefined' }); assert.equal(output.symbols.filter(row => row.name === 'Root').length, 1); assert.equal(output.signatures.length, 1); assert.deepEqual(output.signatures[0].target, { state: 'observed', ref: output.signatures[0].ref }); assert.equal(graph.provenance().queueProcessed, graph.provenance().queueRecords); assert.equal(output.semanticPublicClosure, false); });
await asyncTest('two distinct native types with the same display remain two structural identities', async () => { const { output } = await fixtureCapture(graphFixture()); assert.equal(output.types.filter(row => row.intrinsicName === 'string').length, 2); assert(output.types.every(row => row.display.interpretation.includes('never'))); });
await asyncTest('unknown aliases and error types retain actual blocker records', async () => { const { output } = await fixtureCapture(graphFixture()); assert(output.unresolvedResults.some(row => row.kind === 'actual-checker-unknown-symbol')); assert(output.unresolvedResults.some(row => row.kind === 'actual-checker-error-type')); assert(output.unsupportedFields.every(row => row.permanentExemption === false && row.semanticQualificationBlocked)); });
function tupleFixture(fields) {
  const fixture = graphFixture(), type = fixture.root.valueType;
  type.names.add('isTupleType'); Object.assign(type, fields); return fixture;
}
await asyncTest('native tuple optional wire absence is retained as mandatory unresolved metadata without fabricated defaults', async () => {
  const { output } = await fixtureCapture(tupleFixture({})), tuple = output.types.find(row => row.kindPredicates.isTupleType);
  for (const field of ['elementFlags','fixedLength','readonly']) {
    assert.deepEqual(tuple[field], { state: 'undefined' });
    assert(output.unresolvedResults.some(row => row.ref === tuple.ref && row.field === field && row.state === 'undefined' && row.semanticQualificationBlocked && !row.permanentExemption));
  }
  assert.equal(output.reachableGraphTraversalCompleted, true); assert.equal(output.fullStructuralInventoryQualified, false);
});
await asyncTest('actual present empty tuple flags zero fixed length and false readonly remain distinct from absent metadata', async () => {
  const { output } = await fixtureCapture(tupleFixture({ elementFlags: [], fixedLength: 0, readonly: false })), tuple = output.types.find(row => row.kindPredicates.isTupleType);
  assert.deepEqual(tuple.elementFlags, []); assert.equal(tuple.fixedLength, 0); assert.equal(tuple.readonly, false);
  assert(!output.unresolvedResults.some(row => row.kind === 'actual-native-missing-tuple-metadata'));
});
await asyncTest('tuple flags preserve original required optional rest variadic ordering and explicit null blockers', async () => {
  const { output } = await fixtureCapture(tupleFixture({ elementFlags: [1,2,4,8], fixedLength: null, readonly: true })), tuple = output.types.find(row => row.kindPredicates.isTupleType);
  assert.deepEqual(tuple.elementFlags, [1,2,4,8]); assert.deepEqual(tuple.fixedLength, { state: 'null' }); assert.equal(tuple.readonly, true);
  assert(output.unresolvedResults.some(row => row.field === 'fixedLength' && row.state === 'null' && row.semanticQualificationBlocked));
});
await asyncTest('invalid actual tuple field shapes fail instead of silently substituting values', async () => {
  for (const fields of [{elementFlags:0},{elementFlags:[NaN]},{fixedLength:-1},{readonly:'false'}])
    await assert.rejects(fixtureCapture(tupleFixture(fields)), /Invalid actual public tuple metadata/);
});
await asyncTest('ordered nullable union, optional syntax, readonly index and negative bigint retained', async () => { const { output } = await fixtureCapture(graphFixture()); const union = output.types.find(row => row.kindPredicates.isUnionType); assert.equal(output.types.find(row => row.ref === union.constituentTypes[0].ref).intrinsicName, 'string'); assert.equal(output.types.find(row => row.ref === union.constituentTypes[1].ref).intrinsicName, 'error'); assert(output.types.some(row => row.indexInfos.some(info => info.isReadonly))); assert.deepEqual(output.types.find(row => row.kindPredicates.isBigIntLiteralType).literalValue, { kind: 'actual-bigint', decimal: '-123' }); assert(output.syntax.some(row => row.fields.some(field => field.name === 'questionToken' && field.value === null))); assert(output.declarations[0].fullText.includes('readonly item?')); });
await asyncTest('actual native AST defaultType is semantically queried and remains syntax evidence', async () => { const { output } = await fixtureCapture(graphFixture()); assert(output.declarations[0].annotatedTypeNodes.some(row => row.field === 'defaultType')); assert(output.operationCounts.some(row => row.method === 'getTypeFromTypeNode' && row.executed > 0)); assert(output.unsupportedFields.some(row => row.field === 'getDefaultFromTypeParameter')); });
await asyncTest('stable references preserve identity relations while raw native IDs stay separate', async () => { const a = await fixtureCapture(graphFixture(0)), b = await fixtureCapture(graphFixture(1000)); assert.deepEqual(a.output, b.output); assert.notDeepEqual(a.graph.provenance().nativeIdentityMap, b.graph.provenance().nativeIdentityMap); });
await asyncTest('missing required checker query fails with an actual operation record', async () => { const fixture = graphFixture(); delete fixture.checker.getPropertiesOfType; const graph = createStructuralInventory(fixture.checker, fixture.project, fixture.enums, fixture.limits); graph.seedModule('unchanged.ts', fixture.root, [fixture.root]); await assert.rejects(graph.finish(), /operation unavailable/); assert(graph.provenance().failures.some(row => row.method === 'getPropertiesOfType')); });
await asyncTest('native rejected query is not converted into a fabricated empty type', async () => { const fixture = graphFixture(); fixture.checker.getTypeOfSymbol = async () => { throw new Error('native rejects this input'); }; const graph = createStructuralInventory(fixture.checker, fixture.project, fixture.enums, fixture.limits); graph.seedModule('unchanged.ts', fixture.root, [fixture.root]); await assert.rejects(graph.finish(), /native rejects/); assert.equal(graph.provenance().failures[0].method, 'getTypeOfSymbol'); });
await asyncTest('full graph overflow hard-fails without hidden truncation', async () => { const fixture = graphFixture(); fixture.limits.types = 1; const graph = createStructuralInventory(fixture.checker, fixture.project, fixture.enums, fixture.limits); graph.seedModule('unchanged.ts', fixture.root, [fixture.root]); await assert.rejects(graph.finish(), StructuralBudgetError); assert.equal(graph.provenance().noTruncation, true); });
await asyncTest('operations budget hard-fails before another native query', async () => { const fixture = graphFixture(); fixture.limits.operations = 1; const graph = createStructuralInventory(fixture.checker, fixture.project, fixture.enums, fixture.limits); graph.seedModule('unchanged.ts', fixture.root, [fixture.root]); await assert.rejects(graph.finish(), StructuralBudgetError); assert.equal(graph.provenance().queryLog.length, 1); });
const schemaTexts = plan.structuralInventory.syntaxSchema.sources.map(path => regular(join(plan.oracle, path)).toString('utf8'));
const declaredKindNames = [...new Set(schemaTexts.flatMap(text => [...text.matchAll(/SyntaxKind\.(\w+)/g)].map(row => row[1])))], staticKindTable = Object.fromEntries(declaredKindNames.map((name, index) => [name,index]));
const staticSchema = parsePublicAstSchema(schemaTexts, staticKindTable);
test('actual public declaration parsing retains generic defaults, mapped and optional syntax', () => { assert(staticSchema.kindFields.get(staticKindTable.TypeParameter).includes('defaultType')); assert(staticSchema.kindFields.get(staticKindTable.MappedType).includes('nameType')); assert(staticSchema.kindFields.get(staticKindTable.NamedTupleMember).includes('questionToken')); assert(staticSchema.kindFields.get(staticKindTable.SourceFile).includes('statements')); assert(staticSchema.declaredInterfaceCount > 200); });
await asyncTest('non-enumerable prototype getters expose real syntax without decoder storage', async () => { const fixture = graphFixture(), parameterNode = fixture.node.typeParameters[0]; delete parameterNode.defaultType; Object.defineProperty(Object.getPrototypeOf(parameterNode), 'defaultType', { configurable: true, get() { return fixture.child; } }); fixture.node._decoder = { executePrivateStorage() { throw new Error('must never be visited'); } }; const { output } = await fixtureCapture(fixture); assert(output.declarations[0].annotatedTypeNodes.some(row => row.field === 'defaultType')); assert(output.syntax.every(row => row.fields.every(field => field.name !== '_decoder'))); });
await asyncTest('native-style lazy array entries are all materialized in original order', async () => { const fixture = graphFixture(), parameterNode = fixture.node.typeParameters[0]; class LazyNodeList extends Array { get 0() { return parameterNode; } get 1() { return fixture.child; } } const list = new LazyNodeList(); list.length = 2; fixture.node.typeParameters = list; const { output } = await fixtureCapture(fixture); const array = output.syntax.find(row => row.items?.length === 2 && row.items.every(item => item.syntaxRef)); assert(array); assert.equal(array.items.length, 2); assert(output.declarations[0].annotatedTypeNodes.some(row => row.field === 'defaultType')); });
await asyncTest('unknown actual native syntax cannot become an empty declaration object', async () => { const fixture = graphFixture(); fixture.node.kind = 987654; const graph = createStructuralInventory(fixture.checker, fixture.project, fixture.enums, fixture.limits); graph.seedModule('unchanged.ts', fixture.root, [fixture.root]); await assert.rejects(graph.finish(), /syntax kind absent/); assert(graph.provenance().failures.some(row => row.method === 'public-AST-syntax-schema')); });
function processFixture(killBehavior = () => true) {
  const child = new EventEmitter(); child.pid = 42; child.killed = false; child.exitCode = null; child.signalCode = null; child.stdin = new EventEmitter(); child.stdout = new EventEmitter(); child.stderr = new EventEmitter(); let kills = 0, nextTimer = 0; const timers = new Map();
  child.kill = () => { kills++; const accepted = killBehavior(); child.killed = accepted; return accepted; };
  return { child, timers: { setTimeout(callback, milliseconds) { const id = ++nextTimer; timers.set(id, { callback, milliseconds }); return id; }, clearTimeout(id) { timers.delete(id); } }, fireNext() { const [id, timer] = timers.entries().next().value; timers.delete(id); timer.callback(); }, activeTimers() { return timers.size; }, kills() { return kills; }, exit(code = 0, signal = null) { child.exitCode = code; child.signalCode = signal; child.emit('exit', code, signal); }, close(code = child.exitCode, signal = child.signalCode) { child.emit('close', code, signal); } };
}
function driverProbe(fixture, limit = 64) { return observeDriverChild(() => fixture.child, 'injected-no-execution', [], {}, { snapshotBytes: limit, driverTimeoutMs: 100 }, fixture.timers); }
await asyncTest('Node exit does not settle before late exact pipe bytes and physical close', async () => {
  const f = processFixture(), promise = driverProbe(f); let settled = false; promise.then(() => { settled = true; }); f.child.emit('spawn'); f.child.stdout.emit('data', Buffer.from([255,0])); f.exit(); await Promise.resolve(); assert.equal(settled, false); assert.equal(f.activeTimers(), 1);
  f.child.stdout.emit('data', Buffer.from('late')); f.child.stderr.emit('data', Buffer.from([128,10])); for (const name of ['stdout','stderr']) { f.child[name].emit('end'); f.child[name].emit('close'); } f.close(); const value = await promise;
  assert(value.stdout.equals(Buffer.from([255,0,...Buffer.from('late')]))); assert(value.stderr.equals(Buffer.from([128,10]))); assert.equal(value.failure, undefined); assert.equal(value.lifecycle.closeObserved, true); assert.equal(value.lifecycle.stdio.stdout.closeObserved, true); assert.equal(value.lifecycle.events.at(-1).kind, 'close'); assert.equal(f.activeTimers(), 0);
});
await asyncTest('Node watchdog records failure and kill refusal but waits unconditionally for close', async () => {
  const f = processFixture(() => false), promise = driverProbe(f); let settled = false; promise.then(() => { settled = true; }); f.fireNext(); await Promise.resolve(); assert.equal(settled, false); assert.equal(f.kills(), 1); f.child.stderr.emit('data', Buffer.from('after-watchdog')); f.exit(1); await Promise.resolve(); assert.equal(settled, false); f.close(); const value = await promise;
  assert.equal(value.failure.kind, 'driver-deadline'); assert.equal(value.lifecycle.terminationRequests[0].returned, false); assert.equal(value.lifecycle.watchdogs[0].fired, true); assert.equal(value.stderr.toString(), 'after-watchdog'); assert.equal(value.lifecycle.exit.code, 1); assert.equal(value.lifecycle.close.code, 1);
});
await asyncTest('Node output overflow keeps bounded prefixes and first failure through later watchdog and exit', async () => {
  const f = processFixture(), promise = driverProbe(f, 3); f.child.stdout.emit('data', Buffer.from('abcde')); f.child.stderr.emit('data', Buffer.from('fg')); f.fireNext(); f.exit(2); f.close(); const value = await promise;
  assert.equal(value.stdout.toString(), 'abc'); assert.equal(value.stderr.length, 0); assert.deepEqual(value.streams.stdout, { observedBytes: 5, capturedBytes: 3, omittedBytes: 2 }); assert.deepEqual(value.streams.stderr, { observedBytes: 2, capturedBytes: 0, omittedBytes: 2 }); assert.equal(value.failure.kind, 'driver-output-overflow'); assert.equal(f.kills(), 1); assert(value.lifecycle.failures.some(row => row.kind === 'driver-deadline')); assert(value.lifecycle.failures.some(row => row.kind === 'child-exit'));
});
await asyncTest('asynchronous spawn error retains metadata and still awaits actual close', async () => {
  const f = processFixture(() => false), promise = driverProbe(f); let settled = false; promise.then(() => { settled = true; }); const error = Object.assign(new Error('spawn denied'), { code: 'EACCES', syscall: 'spawn', path: 'injected' }); f.child.emit('error', error); await Promise.resolve(); assert.equal(settled, false); f.close(-2, null); const value = await promise;
  assert.equal(value.failure.kind, 'child-error'); assert.equal(value.failure.code, 'EACCES'); assert.equal(value.lifecycle.closeObserved, true); assert.equal(value.lifecycle.exitObserved, false); assert.equal(value.lifecycle.errors[0].path, 'injected');
});
await asyncTest('synchronous spawn throw records no returned handle and no invented close witness', async () => {
  const value = await observeDriverChild(() => { throw Object.assign(new Error('synchronous spawn failure'), { code: 'EINVAL' }); }, 'injected', [], {}, { snapshotBytes: 3, driverTimeoutMs: 100 }); assert.equal(value.failure.kind, 'synchronous-spawn-error'); assert.equal(value.failure.code, 'EINVAL'); assert.equal(value.lifecycle.ownedChildHandleReturned, false); assert.equal(value.lifecycle.closeObserved, false); assert.equal(value.stdout.length, 0);
});
await asyncTest('kill exception is secondary evidence and never causes timeout detach', async () => {
  const f = processFixture(() => { throw new Error('kill failed'); }), promise = driverProbe(f); let settled = false; promise.then(() => { settled = true; }); f.fireNext(); await Promise.resolve(); assert.equal(settled, false); f.exit(0); f.close(); const value = await promise; assert.equal(value.failure.kind, 'driver-deadline'); assert(value.lifecycle.failures.some(row => row.kind === 'termination-request-error')); assert.equal(value.lifecycle.terminationRequests[0].error.kind, 'termination-request-error'); assert.equal(value.lifecycle.terminationRequests[0].error.message, 'kill failed'); assert.notEqual(value.failure.message, value.lifecycle.terminationRequests[0].error.message); assert.equal(value.failure, value.lifecycle.failures[0]);
});
await asyncTest('separate exit and close disagreements remain raw failed evidence', async () => {
  const f = processFixture(), promise = driverProbe(f); f.exit(0); f.close(1, null); const value = await promise; assert.deepEqual(value.lifecycle.exit, { code: 0, signal: null }); assert.deepEqual(value.lifecycle.close, { code: 1, signal: null }); assert(value.lifecycle.failures.some(row => row.kind === 'exit-close-disagreement'));
});
await asyncTest('stream failure is retained until child close and preserves following stderr bytes', async () => {
  const f = processFixture(), promise = driverProbe(f); f.child.stdout.emit('error', Object.assign(new Error('pipe failed'), { code: 'EIO' })); f.child.stderr.emit('data', Buffer.from('diagnostic')); f.exit(); f.close(); const value = await promise; assert.equal(value.failure.kind, 'stdout-error'); assert.equal(value.lifecycle.stdio.stdout.errors[0].code, 'EIO'); assert.equal(value.stderr.toString(), 'diagnostic');
});
await asyncTest('native close installed at spawn is preserved even before guard finish begins', async () => {
  const f = processFixture(), observer = observeOwnedChildClose(f.child, 'native compiler helper', f.timers); observer.armDeadline('native-operation-deadline', 90); f.child.emit('spawn'); f.exit(); f.child.stdin.emit('finish'); f.child.stdin.emit('close'); f.child.stdout.emit('end'); f.child.stdout.emit('close'); f.close(); const value = await awaitExit(f.child, 30, observer);
  assert.equal(value.physicalCloseObserved, true); assert.equal(value.closeAwaited, true); assert.equal(value.exitAwaited, true); assert.equal(value.observation.stdio.stdout.endObserved, true); assert.equal(value.observation.stdio.stdin.finishObserved, true); assert.equal(value.observation.watchdogs[1].armed, false); assert.equal(f.activeTimers(), 0);
});
await asyncTest('native thirty-second close watchdog fails but joins subsequent physical close', async () => {
  const f = processFixture(), observer = observeOwnedChildClose(f.child, 'native compiler helper', f.timers), promise = awaitExit(f.child, 30, observer); let settled = false; promise.then(() => { settled = true; }, () => { settled = true; }); f.exit(); f.fireNext(); await Promise.resolve(); assert.equal(settled, false); assert.equal(observer.observation.watchdogs[0].milliseconds, 30); assert.equal(f.kills(), 1); f.close(); await assert.rejects(promise, error => error.firstFailure.kind === 'native-close-deadline' && error.ownedChildLifecycle.closeObserved === true);
});
await asyncTest('native operation deadline remains first failure after finish deadline and signals', async () => {
  const f = processFixture(), observer = observeOwnedChildClose(f.child, 'native compiler helper', f.timers); observer.armDeadline('native-operation-deadline', 90); f.fireNext(); const promise = awaitExit(f.child, 30, observer); f.fireNext(); assert.equal(f.kills(), 1); f.exit(null, 'SIGTERM'); f.close(); await assert.rejects(promise, error => error.firstFailure.kind === 'native-operation-deadline'); assert.equal(observer.observation.watchdogs.filter(row => row.fired).length, 2); assert.deepEqual(observer.observation.close, { code: null, signal: 'SIGTERM' });
});
await asyncTest('native observer requires exact owned child identity and genuine exit witness', async () => {
  const f = processFixture(), observer = observeOwnedChildClose(f.child, 'native compiler helper', f.timers); await assert.rejects(awaitExit(new EventEmitter(), 30, observer), /exact spawned helper/); const promise = awaitExit(f.child, 30, observer); f.close(0, null); await assert.rejects(promise, error => error.firstFailure.kind === 'missing-exit-witness');
});
await asyncTest('native termination ends owned stdin before kill without certifying close early', async () => {
  const f = processFixture(), order = []; f.child.stdin.end = () => { order.push('stdin-end'); }; f.child.kill = () => { order.push('kill'); return true; }; const observer = observeOwnedChildClose(f.child, 'native compiler helper', f.timers); observer.noteFailure('native-query-failure', new Error('first failure')); observer.requestTermination('native-query-failure'); assert.deepEqual(order, ['stdin-end','kill']); assert.equal(observer.observation.closeObserved, false); observer.requestTermination('second failure'); assert.equal(order.length, 2); f.exit(1); f.close(); const value = await observer.wait(); assert.equal(value.firstFailure.kind, 'native-query-failure'); assert.equal(value.observation.terminationRequests[0].stdinEndReturned, true);
});
await asyncTest('owned stdin-end error preserves first failure and still requests kill and joins close', async () => {
  const f = processFixture(); f.child.stdin.end = () => { throw new Error('EOF request failed'); }; const observer = observeOwnedChildClose(f.child, 'native compiler helper', f.timers); observer.armDeadline('native-close-deadline', 30); f.fireNext(); assert.equal(f.kills(), 1); assert.equal(observer.observation.closeObserved, false); f.exit(1); f.close(); const value = await observer.wait(); assert.equal(value.firstFailure.kind, 'native-close-deadline'); assert(value.observation.failures.some(row => row.kind === 'termination-stdin-end-error')); assert.equal(value.observation.terminationRequests[0].stdinEndError.kind, 'termination-stdin-end-error'); assert.equal(value.observation.terminationRequests[0].stdinEndError.message, 'EOF request failed'); assert.notEqual(value.firstFailure.message, value.observation.terminationRequests[0].stdinEndError.message); assert.equal(value.firstFailure, value.observation.failures[0]);
});
await asyncTest('stdin EOF and kill failures retain their own cause receipts while first deadline and close join stay authoritative', async () => {
  const f = processFixture(() => { throw Object.assign(new Error('actual secondary kill failure'), { code: 'EPERM', syscall: 'kill' }); }); f.child.stdin.end = () => { throw Object.assign(new Error('actual secondary EOF failure'), { code: 'EPIPE', syscall: 'end' }); }; const observer = observeOwnedChildClose(f.child, 'native compiler helper', f.timers); observer.armDeadline('native-close-deadline', 30); f.fireNext(); const first = observer.firstFailure(), request = observer.observation.terminationRequests[0];
  assert.equal(first.kind, 'native-close-deadline'); assert.equal(request.stdinEndError.message, 'actual secondary EOF failure'); assert.equal(request.stdinEndError.code, 'EPIPE'); assert.equal(request.stdinEndError.syscall, 'end'); assert.equal(request.error.message, 'actual secondary kill failure'); assert.equal(request.error.code, 'EPERM'); assert.equal(request.error.syscall, 'kill'); assert.equal(request.stdinEndError, observer.observation.failures[1]); assert.equal(request.error, observer.observation.failures[2]); assert.equal(observer.observation.events.find(row => row.kind === 'termination-stdin-end-error').error, request.stdinEndError); assert.equal(observer.observation.events.find(row => row.kind === 'termination-request-error').error, request.error);
  const promise = observer.requireSuccessfulClose(); let settled = false; promise.then(() => { settled = true; }, () => { settled = true; }); f.exit(1); await Promise.resolve(); assert.equal(settled, false); assert.equal(observer.firstFailure(), first); f.close(); await assert.rejects(promise, error => error.firstFailure === first && error.ownedChildLifecycle.closeObserved === true); assert.equal(observer.firstFailure(), first);
});
await asyncTest('API cleanup failures do not skip or detach actual native close join', async () => {
  const f = processFixture(), observer = observeOwnedChildClose(f.child, 'native compiler helper', f.timers), order = [], promise = finishNativeSession({ async dispose() { order.push('dispose'); throw new Error('dispose failed first'); } }, { async close() { order.push('api-close'); throw new Error('API close failed second'); } }, { async finish() { order.push('guard-finish'); return awaitExit(f.child, 30, observer); } }); let settled = false; promise.then(() => { settled = true; });
  for (let i = 0; i < 8; i++) await Promise.resolve(); assert.deepEqual(order, ['dispose','api-close','guard-finish']); assert.equal(settled, false); f.exit(); f.close(); const value = await promise; assert.equal(value.failure.message, 'dispose failed first'); assert.deepEqual(value.steps.map(row => row.completed), [false,false,true]); assert.equal(value.steps[1].error.message, 'API close failed second'); assert.equal(value.lifecycle.physicalCloseObserved, true);
});
test('successful driver exit cannot substitute for actual native close provenance', () => {
  const value = { lifecycle: { exitAwaited: true, closeAwaited: true, physicalCloseObserved: true }, nativeChildLifecycle: { exitObserved: true, closeObserved: true, exit: { code: 0, signal: null }, close: { code: 0, signal: null } }, protocol: { complete: true, omittedRawBytes: 0 } }; assertPhysicalNativeClose(value); for (const mutate of [x => x.lifecycle.closeAwaited = false, x => x.nativeChildLifecycle.closeObserved = false, x => x.nativeChildLifecycle.close.code = 1, x => x.protocol.complete = false, x => x.nativeFirstFailure = { kind: 'watchdog' }]) { const changed = structuredClone(value); mutate(changed); assert.throws(() => assertPhysicalNativeClose(changed)); }
});
function memoryEvidenceIo(maxRead = 7, maxWrite = 13) {
  const files = new Map(), handles = new Map(), trace = []; let serial = 0;
  const io = { files, trace, open(path) { assert(!files.has(path), 'Existing evidence preserved'); const descriptor = ++serial; files.set(path, Buffer.alloc(0)); handles.set(descriptor, { path, offset: 0, output: [] }); trace.push({ kind: 'open-exclusive', path }); return descriptor; }, write(descriptor, buffer, offset, count) { const handle = handles.get(descriptor), size = Math.min(count, maxWrite); handle.output.push(Buffer.from(buffer.subarray(offset, offset + size))); return size; }, close(descriptor) { const handle = handles.get(descriptor); assert(handle); if (handle.output) files.set(handle.path, Buffer.concat(handle.output)); handles.delete(descriptor); trace.push({ kind: 'close', path: handle.path }); }, openRead(path) { assert(files.has(path), 'Missing evidence'); const descriptor = ++serial; handles.set(descriptor, { path, offset: 0 }); return descriptor; }, read(descriptor, buffer, offset, count) { const handle = handles.get(descriptor), data = files.get(handle.path), size = Math.min(maxRead, count, data.length - handle.offset); data.copy(buffer, offset, handle.offset, handle.offset + size); handle.offset += size; return size; }, stat(descriptor) { const size = files.get(handles.get(descriptor).path).length; return { isFile: () => true, size }; }, small(path, maximum) { assert(files.has(path), 'Missing small evidence'); const value = files.get(path); assert(value.length <= maximum); return value; }, openHandles() { return handles.size; } }; return io;
}
const encodingLimits = { snapshotBytes: 1048576, fileBytes: 1048576, jsonNodes: 100000, jsonDepth: 128, protocolBytes: 2147483648 };
const memoryRoot = resolve('P:/PiSharp/public-fixtures/structural-memory-no-directory'), memoryOutput = join(memoryRoot, 'first.json');
function memoryReceipt(io, budget) { const value = { schemaVersion: 1, joined: true }; const pin = writeStreamedEvidence(memoryRoot, memoryOutput + '.native-receipt.json', [value], budget, io); return { suffix: '.native-receipt.json', bytes: pin.bytes, sha256: pin.sha256 }; }
function decodeMemoryBundle(manifest, io) { function visit(node) { if (node.representation === 'inline') return node.value; if (node.representation === 'object') return Object.fromEntries(node.fields.map(row => [row.name,visit(row.value)])); const part = manifest.parts[node.ordinal], rows = io.files.get(memoryOutput + part.suffix).toString('utf8').split('\n').filter(Boolean).map(line => JSON.parse(line)); return part.valueKind === 'ordered-array' ? rows.map(row => row.value) : rows[0].value; } return visit(manifest.shape); }
test('streamed JSON preserves full scalar/array/object values and surrogate-boundary escapes', () => {
  const value = { exact: 'a'.repeat(4095) + '🙂\n\u0000\ud800' + 'b'.repeat(5000), array: [undefined,null,false,-0], optional: undefined, nested: { quote: '\\"' } }, budget = createEncodingBudget(encodingLimits), bytes = Buffer.concat([...streamingJsonChunks(value,budget)]); assert.equal(bytes.toString('utf8'), JSON.stringify(value)); assert.deepEqual(JSON.parse(bytes), JSON.parse(JSON.stringify(value))); assert(budget.counts().nodes > 0);
});
test('streamed evidence closes partial-write handles and counts actual admitted encoded bytes', () => {
  const io = memoryEvidenceIo(3,1), budget = createEncodingBudget(encodingLimits), value = { rawId: 987, order: [2,1,0] }, pin = writeStreamedEvidence(memoryRoot, memoryOutput, [value], budget, io), expected = Buffer.from(JSON.stringify(value) + '\n'); assert(io.files.get(memoryOutput).equals(expected)); assert.equal(pin.bytes,expected.length); assert.equal(pin.sha256,hash(expected)); assert.equal(budget.counts().bytes,expected.length); assert.equal(io.openHandles(),0); assert.throws(() => writeStreamedEvidence(memoryRoot,memoryOutput,[value],budget,io),/Existing evidence/);
});
test('sidecars reconstruct every full raw ID, duplicate handle and original field/query order', () => {
  const io=memoryEvidenceIo(), budget=createEncodingBudget(encodingLimits), receipt=memoryReceipt(io,budget), original={ rawHandles:[{id:72,path:'C:\\same\\raw.ts'},{id:72,path:'C:\\same\\raw.ts'}], structuralGraph:{projectId:44,nativeIdentityMap:[{ref:'t0',nativeIdentity:981},{ref:'t1',nativeIdentity:17}],queryLog:[{order:0,method:'first'},{order:1,method:'second'}],failures:[]}, fsRequests:[{method:'readFile',path:'C:\\literal\\path.ts',admitted:true}], hugeExactString:'🙂'.repeat(3000), nullValue:null, zero:-0 }, written=writeProvenanceBundle(memoryRoot,memoryOutput,original,budget,receipt,io), verified=verifyProvenanceBundle(memoryOutput,encodingLimits,io);
  // Exercise the read-back consumer, not the pre-serialization manifest object. JSON's existing
  // numeric wire representation converts -0 to 0; the original raw protocol remains separate.
  const reconstructed=decodeMemoryBundle(verified.manifest,io);
  assert.deepEqual(reconstructed,JSON.parse(JSON.stringify(original))); assert(Object.is(reconstructed.zero,0));
  assert.deepEqual(verified.manifest.parts.map(row=>row.fieldPath),[['rawHandles'],['structuralGraph','nativeIdentityMap'],['structuralGraph','queryLog'],['structuralGraph','failures'],['fsRequests'],['hugeExactString']]); assert.equal(verified.aggregateBytes,budget.counts().bytes); assert.equal(io.openHandles(),0);
});
test('receipt and manifest consume the same aggregate budget as all ordered sidecars', () => {
  const io=memoryEvidenceIo(), generous=createEncodingBudget(encodingLimits), receipt=memoryReceipt(io,generous), written=writeProvenanceBundle(memoryRoot,memoryOutput,{rows:[{value:'abc'}]},generous,receipt,io); const aggregate=receipt.bytes+written.pin.bytes+written.manifest.parts.reduce((sum,row)=>sum+row.bytes,0); assert.equal(verifyProvenanceBundle(memoryOutput,encodingLimits,io).aggregateBytes,aggregate); assert.equal(generous.counts().bytes,aggregate); const boundary=Buffer.byteLength(JSON.stringify({value:'abc'})+'\n'), exactIo=memoryEvidenceIo();assert.equal(writeStreamedEvidence(memoryRoot,memoryOutput,[{value:'abc'}],createEncodingBudget({...encodingLimits,snapshotBytes:boundary}),exactIo).bytes,boundary);assert.throws(()=>writeStreamedEvidence(memoryRoot,memoryOutput,[{value:'abc'}],createEncodingBudget({...encodingLimits,snapshotBytes:boundary-1}),memoryEvidenceIo()),/Aggregate encoded evidence byte budget/);
});
test('repinned reordered raw observations still fail explicit ordinal verification', () => {
  const io=memoryEvidenceIo(), budget=createEncodingBudget(encodingLimits), receipt=memoryReceipt(io,budget), written=writeProvenanceBundle(memoryRoot,memoryOutput,{rows:[{id:9},{id:4}]},budget,receipt,io), part=written.manifest.parts[0], lines=io.files.get(memoryOutput+part.suffix).toString().trimEnd().split('\n'), changed=Buffer.from(lines.reverse().join('\n')+'\n'); io.files.set(memoryOutput+part.suffix,changed); part.sha256=hash(changed); io.files.set(memoryOutput+'.provenance.json',Buffer.from(JSON.stringify(written.manifest)+'\n')); assert.throws(()=>verifyProvenanceBundle(memoryOutput,encodingLimits,io),/order\/framing/);
});
test('missing, changed, duplicate and escaping sidecars never certify complete provenance', () => {
  for(const mutate of [(m,io)=>io.files.delete(memoryOutput+m.parts[0].suffix),(m,io)=>io.files.set(memoryOutput+m.parts[0].suffix,Buffer.from('changed\n')),(m)=>m.parts.push({...m.parts[0]}),(m)=>m.parts[0].suffix='../outside.jsonl',(m)=>m.shape.fields.push({...m.shape.fields[0]}),(m)=>m.parts[0].fieldPath=['wrong']]){const io=memoryEvidenceIo(),budget=createEncodingBudget(encodingLimits),receipt=memoryReceipt(io,budget),written=writeProvenanceBundle(memoryRoot,memoryOutput,{rows:[{id:8}]},budget,receipt,io);mutate(written.manifest,io);io.files.set(memoryOutput+'.provenance.json',Buffer.from(JSON.stringify(written.manifest)+'\n'));assert.throws(()=>verifyProvenanceBundle(memoryOutput,encodingLimits,io));assert.equal(io.openHandles(),0);}
});
test('byte, node, depth and cyclic evidence failures retain partial files without raising limits', () => {
  for(const [value,limits] of [[{text:'abcdef'},{...encodingLimits,snapshotBytes:8}],[{rows:[1,2,3]},{...encodingLimits,jsonNodes:3}],[{nested:{leaf:1}},{...encodingLimits,jsonDepth:1}]]){const io=memoryEvidenceIo();assert.throws(()=>writeStreamedEvidence(memoryRoot,memoryOutput,[value],createEncodingBudget(limits),io));assert.equal(io.openHandles(),0);assert(io.files.get(memoryOutput).length<=limits.snapshotBytes);}
  const cyclic={};cyclic.self=cyclic;const io=memoryEvidenceIo();assert.throws(()=>writeStreamedEvidence(memoryRoot,memoryOutput,[cyclic],createEncodingBudget(encodingLimits),io),/cyclic/);assert.equal(io.openHandles(),0);
  const nestedIo=memoryEvidenceIo(),nestedBudget=createEncodingBudget({...encodingLimits,jsonDepth:4});assert.throws(()=>writeProvenanceBundle(memoryRoot,memoryOutput,{outer:{list:[{deep:{leaf:1}}]}},nestedBudget,{suffix:'.native-receipt.json',bytes:0,sha256:hash(Buffer.alloc(0))},nestedIo),/node\/depth/);assert.equal(nestedIo.files.has(memoryOutput+'.provenance.json'),false);assert.equal(nestedIo.openHandles(),0);
});
test('consumer verifies every exact physical protocol byte under the unchanged raw traffic admission', () => {
  const io=memoryEvidenceIo(),bytes=Buffer.from('{"direction":"native-to-client","base64":"YWJj"}\n');io.files.set(memoryOutput+'.protocol.jsonl',bytes);const protocol={path:memoryOutput+'.protocol.jsonl',chunks:1,rawBytes:3,capturedRawBytes:3,omittedRawBytes:0,fileBytes:bytes.length,complete:true,writeFailure:false,overflow:false,sha256:hash(bytes)};assert.equal(verifyProtocolEvidence(memoryOutput,protocol,encodingLimits,io).bytes,bytes.length);for(const patch of [{rawBytes:4},{capturedRawBytes:2147483649,rawBytes:2147483649},{path:memoryOutput+'.wrong'},{complete:false},{writeFailure:true},{sha256:'0'.repeat(64)}])assert.throws(()=>verifyProtocolEvidence(memoryOutput,{...protocol,...patch},encodingLimits,io));
});
test('bounded receipt text hashes full errors and requires exact oversized text in provenance', () => {
  const error=Object.assign(new TypeError('x'.repeat(5000)+'🙂'),{code:'EPIPE'}),identity=failureIdentity(error);assert.equal(identity.name.inline,'TypeError');assert.equal(identity.message.inline,undefined);assert.equal(identity.message.utf8Bytes,Buffer.byteLength(error.message));assert.equal(identity.message.sha256,hash(Buffer.from(error.message)));assert.equal(identity.message.completeTextInFullProvenanceRequired,true);assert.equal(textIdentity('a'.repeat(4095)+'🙂').sha256,hash(Buffer.from('a'.repeat(4095)+'🙂')));
});
function persistenceGuard(trace=[]) { return { lifecycleReceipt(){trace.push('joined-receipt');return { ownedNativeHandles:1,nativeChildLifecycle:{exitObserved:true,closeObserved:true,exit:{code:0,signal:null},close:{code:0,signal:null}},protocol:{path:memoryOutput+'.protocol.jsonl',chunks:0,rawBytes:0,capturedRawBytes:0,omittedRawBytes:0,fileBytes:0,complete:true,writeFailure:false,overflow:false,sha256:hash(Buffer.alloc(0))} };} }; }
const persistencePlan={limits:encodingLimits,receipt:{sha256:'pinned-actual-receipt'}};
await asyncTest('first query exception survives later verification and provenance encoding failures with native receipt retained',async()=>{
  const io=memoryEvidenceIo(),first=new TypeError('actual first native query failure'),second=new Error('later after-verification failure'),trace=[],cleanup={lifecycle:{exitAwaited:true,closeAwaited:true,physicalCloseObserved:true},steps:[{name:'guard.finish',completed:true}]};let caught;
  try{await persistCaptureArtifacts('oracle',memoryRoot,memoryOutput,persistencePlan,persistenceGuard(trace),cleanup,first,()=>{trace.push('large');const cyclic={};cyclic.self=cyclic;return {cyclic};},{io,verify:async()=>{trace.push('verify');throw second;}});}catch(error){caught=error;}
  assert.equal(caught,first);assert.equal(caught.captureEvidenceFailures[0].error,second);assert.equal(caught.captureEvidenceFailures[1].stage,'full-provenance-encoding');const receipt=JSON.parse(io.files.get(memoryOutput+'.native-receipt.json'));assert.equal(receipt.failure.message.inline,first.message);assert.equal(receipt.nativeChildLifecycle.closeObserved,true);assert.equal(receipt.fullCaptureQualified,false);assert.deepEqual(trace,['joined-receipt','verify','large']);assert.equal(io.openHandles(),0);
});
await asyncTest('early receipt exists before verification and large provenance are entered',async()=>{
  const io=memoryEvidenceIo(),trace=[],cleanup={lifecycle:{exitAwaited:true,closeAwaited:true,physicalCloseObserved:true},steps:[]};const result=await persistCaptureArtifacts('oracle',memoryRoot,memoryOutput,persistencePlan,persistenceGuard(trace),cleanup,undefined,()=>{assert(io.files.has(memoryOutput+'.native-receipt.json'));trace.push('large');return {rawHandles:[{id:1}]};},{io,verify:async()=>{assert(io.files.has(memoryOutput+'.native-receipt.json'));trace.push('verify');}});assert.deepEqual(trace,['joined-receipt','verify','large']);assert(result.manifest.complete);assert.equal(verifyProvenanceBundle(memoryOutput,encodingLimits,io).aggregateBytes,result.aggregate.bytes);
});
await asyncTest('held injected native close prevents every capture receipt and encoding attempt',async()=>{
  const f=processFixture(),observer=observeOwnedChildClose(f.child,'native compiler helper',f.timers),io=memoryEvidenceIo(),guard={...persistenceGuard(),finish(){return awaitExit(f.child,30,observer);}},promise=finishNativeSession(undefined,{async close(){}},guard).then(cleanup=>persistCaptureArtifacts('oracle',memoryRoot,memoryOutput,persistencePlan,guard,cleanup,undefined,()=>({raw:[1,2]}),{io,verify:async()=>{}}));let settled=false;promise.then(()=>{settled=true;});f.exit();for(let i=0;i<8;i++)await Promise.resolve();assert.equal(settled,false);assert.equal(io.files.size,0);f.close();await promise;assert(io.files.has(memoryOutput+'.native-receipt.json'));assert.equal(observer.observation.closeObserved,true);
});
await asyncTest('aggregate provenance overflow preserves early receipt and original query exception',async()=>{
  const io=memoryEvidenceIo(),first=new Error('original query failure'),cleanup={lifecycle:{exitAwaited:true,closeAwaited:true,physicalCloseObserved:true},steps:[]},small={...persistencePlan,limits:{...encodingLimits,snapshotBytes:16384}};await assert.rejects(persistCaptureArtifacts('oracle',memoryRoot,memoryOutput,small,persistenceGuard(),cleanup,first,()=>({huge:'x'.repeat(32768)}),{io,verify:async()=>{}}),error=>error===first&&error.captureEvidenceFailures.some(row=>/Aggregate encoded evidence byte budget/.test(row.error.message)));assert.equal(JSON.parse(io.files.get(memoryOutput+'.native-receipt.json')).failure.message.inline,first.message);assert.equal(io.openHandles(),0);assert.throws(()=>verifyProvenanceBundle(memoryOutput,small.limits,io));
});
await asyncTest('frozen first exception survives receipt-state and encoding failures without attachment masking',async()=>{
  const io=memoryEvidenceIo(),first=Object.freeze(new TypeError('frozen original query failure')),secondary=new Error('receipt state unavailable'),guard={lifecycleReceipt(){throw secondary;}},cleanup={steps:[]};await assert.rejects(persistCaptureArtifacts('oracle',memoryRoot,memoryOutput,persistencePlan,guard,cleanup,first,()=>{throw new Error('later provenance unavailable');},{io,verify:async()=>{}}),error=>error===first);assert.equal(captureEvidenceFailures(first)[0].error,secondary);const receipt=JSON.parse(io.files.get(memoryOutput+'.native-receipt.json'));assert.equal(receipt.failure.message.inline,first.message);assert.equal(receipt.nativeJoinReceiptStateUnavailable,true);assert.equal(receipt.nativeChildLifecycle,undefined);assert.equal(io.openHandles(),0);
});
// Authored fake-compiler controls only: no new reference or native execution.
const retainedPanicMessage = 'panic: interface conversion: checker.TypeData is *checker.TypeReference, not *checker.TupleType';
function retainedPanic() { return Object.assign(new Error(retainedPanicMessage + '\noriginal fake stack payload'), { code: -32603 }); }
function symbolIsolationFixture(failedNames = ['item']) {
  const fixture = graphFixture(), original = fixture.checker.getTypeOfSymbol, errors = [];
  fixture.checker.getTypeOfSymbol = async symbol => {
    if (failedNames.includes(symbol.name)) { const error = retainedPanic(); errors.push(error); throw error; }
    return original.call(fixture.checker, symbol);
  };
  const graph = createStructuralInventory(fixture.checker, fixture.project, fixture.enums, fixture.limits, { isolateSymbolTypePanic: true });
  graph.seedModule('unchanged.ts', fixture.root, [fixture.root,fixture.alias,fixture.unknown]);
  return { fixture, graph, errors };
}
test('symbol isolation accepts only the exact retained native API code and panic signature', () => {
  assert(isRetainedSymbolTypePanic(retainedPanic()));
  for (const error of [new Error(retainedPanicMessage), Object.assign(new Error(retainedPanicMessage), { code: '-32603' }),
    Object.assign(new Error(retainedPanicMessage + '-different'), { code: -32603 }),
    Object.assign(new Error('transport failed'), { code: -32603 }), new StructuralBudgetError(retainedPanicMessage)])
    assert.equal(isRetainedSymbolTypePanic(error), false);
});
await asyncTest('one failed symbol retains every independently successful symbol and complete failure provenance', async () => {
  const { graph, errors } = symbolIsolationFixture(), output = await graph.finish();
  const failed = output.symbols.find(row => row.name === 'item');
  assert.equal(failed.valueType.state, 'unresolved'); assert.equal(Object.hasOwn(failed.valueType,'ref'), false);
  for (const name of ['Root','method','arg','distinct','bigint']) assert.equal(output.symbols.find(row => row.name === name).valueType.state,'observed');
  assert.deepEqual(failed.parent,{state:'undefined'}); assert.equal(failed.exportSymbol.ref,failed.ref);
  assert.deepEqual(failed.members,[]); assert.deepEqual(failed.exports,[]);
  const unresolved=output.unresolvedResults.find(row=>row.ref===failed.ref&&row.kind==='actual-native-symbol-value-type-query-failure');
  assert.equal(unresolved.nativeSymbolId,13); assert.equal(unresolved.method,'getTypeOfSymbol');
  assert.equal(unresolved.error.message,errors[0].message); assert.equal(unresolved.error.stack,errors[0].stack); assert.equal(unresolved.error.code,-32603);
  assert(unresolved.semanticQualificationBlocked); assert.equal(unresolved.permanentExemption,false);
  const raw=graph.provenance(); assert.equal(raw.queryLog[unresolved.queryOrder].error,unresolved.error);
  assert.equal(raw.failures.length,1); assert.equal(raw.queueProcessed,raw.queueRecords); assert(raw.noTruncation);
  assert.equal(graph.isolatedFailure(),errors[0]); assert.equal(output.reachableGraphTraversalCompleted,false);
  assert.equal(output.existingWorkQueueDrainedWithUnresolvedQueries,true); assert.equal(output.fullStructuralInventoryQualified,false); assert.equal(output.semanticPublicClosure,false);
});
await asyncTest('a failed value facet does not replace an independently returned declared type or hide descendants', async () => {
  const { graph }=symbolIsolationFixture(['Root']),output=await graph.finish(),root=output.symbols.find(row=>row.name==='Root');
  assert.equal(root.valueType.state,'unresolved'); assert.equal(root.declaredType.state,'observed');
  assert.equal(root.members[0].symbol.ref,root.ref); assert(output.symbols.some(row=>row.name==='item'&&row.valueType.state==='observed'));
  assert.equal(output.types.find(row=>row.ref===root.declaredType.ref).kindPredicates.isObjectType,true);
});
await asyncTest('multiple affected symbols remain distinct unresolved observations and preserve the first original cause', async () => {
  const {graph,errors}=symbolIsolationFixture(['Root','item']),output=await graph.finish();
  const rows=output.unresolvedResults.filter(row=>row.kind==='actual-native-symbol-value-type-query-failure');
  assert.equal(rows.length,2); assert.equal(new Set(rows.map(row=>row.ref)).size,2); assert.equal(new Set(rows.map(row=>row.queryOrder)).size,2);
  assert.equal(graph.provenance().failures.length,2); assert.equal(graph.isolatedFailure(),errors[0]);
  assert.equal(output.operationCounts.find(row=>row.method==='getTypeOfSymbol').failures,2); assert.equal(output.reachableGraphTraversalCompleted,false);
});
await asyncTest('legacy graph callers remain fail-fast even for the retained panic unless isolation is explicit', async () => {
  const {fixture,errors}=symbolIsolationFixture(['Root']);
  const graph=createStructuralInventory(fixture.checker,fixture.project,fixture.enums,fixture.limits);graph.seedModule('unchanged.ts',fixture.root,[fixture.root]);
  await assert.rejects(graph.finish(),error=>error===errors[0]); assert.equal(graph.isolatedFailure(),undefined);
});
await asyncTest('other query failures and the same panic in a different operation still abort traversal', async () => {
  for(const method of ['getTypeOfSymbol','getDeclaredTypeOfSymbol']) {
    const {fixture,graph}=symbolIsolationFixture([]),error=method==='getTypeOfSymbol'?new Error('transport stopped'):retainedPanic();
    fixture.checker[method]=async()=>{throw error;};await assert.rejects(graph.finish(),actual=>actual===error);assert.equal(graph.isolatedFailure(),undefined);
  }
});
await asyncTest('later hard budget failure preserves the first isolated panic and extracted partial rows', async () => {
  const {fixture,graph,errors}=symbolIsolationFixture(['Root']);fixture.limits.types=1;let later;
  try{await graph.finish();}catch(error){later=error;}assert(later instanceof StructuralBudgetError);
  assert.equal(retainStructuralFailure(graph,later),errors[0]);assert.equal(captureEvidenceFailures(errors[0])[0].error,later);
  const partial=graph.partialObservation();assert.equal(partial.symbols[0].valueType.state,'unresolved');assert.equal(partial.reachableGraphTraversalCompleted,false);
  assert.equal(partial.fullStructuralInventoryQualified,false);assert.equal(graph.provenance().queueProcessed<=graph.provenance().queueRecords,true);
});
test('profile admission rejects semantic substitution and passing or broadened isolation policy', () => {
  for(const mutate of [p=>p.symbolQueryFailureIsolation.fullCaptureMustFail=false,p=>p.symbolQueryFailureIsolation.substituteSemanticFacts=true,
    p=>p.symbolQueryFailureIsolation.method='getTypeFromTypeNode',p=>p.symbolQueryFailureIsolation.errorCode=null,
    p=>p.symbolQueryFailureIsolation.panicPrefix='panic:',p=>p.symbolQueryFailureIsolation.partialObservationSuffix='.json',
    p=>p.symbolQueryFailureIsolation.referenceExecutionQualified=true]){const copy=structuredClone(plan);mutate(copy);assert.throws(()=>assertProfilePlan(copy));}
});
await asyncTest('partial observation and complete provenance persist while the mandatory full capture still throws',async()=>{
  const {graph,errors}=symbolIsolationFixture(),output=await graph.finish(),first=errors[0],io=memoryEvidenceIo(),cleanup={lifecycle:{exitAwaited:true,closeAwaited:true,physicalCloseObserved:true},steps:[]};
  await assert.rejects(persistCaptureArtifacts('oracle',memoryRoot,memoryOutput,persistencePlan,persistenceGuard(),cleanup,first,
    ()=>({structuralGraph:graph.provenance()}),{io,verify:async()=>{},partialObservation:()=>({kind:'incomplete-recursive-structural-observation',fullStructuralInventoryQualified:false,semanticPublicClosure:false,structuralTypeInventory:output})}),error=>error===first);
  assert.equal(io.files.has(memoryOutput),false);assert(io.files.has(memoryOutput+'.partial.json'));
  const partial=JSON.parse(io.files.get(memoryOutput+'.partial.json'));assert.equal(partial.structuralTypeInventory.symbols.length,output.symbols.length);assert.equal(partial.semanticPublicClosure,false);
  const verified=verifyProvenanceBundle(memoryOutput,encodingLimits,io),decoded=decodeMemoryBundle(verified.manifest,io);
  assert.deepEqual(decoded.structuralGraph,JSON.parse(JSON.stringify(graph.provenance())));
  assert.equal(decoded.failure.code,-32603);assert.equal(decoded.failure.stack,first.stack);
  assert.equal(decoded.partialObservationPin.sha256,hash(io.files.get(memoryOutput+'.partial.json')));
  assert.equal(decoded.partialObservationPin.bytes,io.files.get(memoryOutput+'.partial.json').length);
  assert.equal(JSON.parse(io.files.get(memoryOutput+'.native-receipt.json')).fullCaptureQualified,false);assert.equal(io.openHandles(),0);
});
await asyncTest('partial observation overflow cannot mask the original panic or certify capture success',async()=>{
  const io=memoryEvidenceIo(),first=retainedPanic(),cleanup={steps:[]},small={...persistencePlan,limits:{...encodingLimits,snapshotBytes:16384}};
  await assert.rejects(persistCaptureArtifacts('oracle',memoryRoot,memoryOutput,small,persistenceGuard(),cleanup,first,()=>({queries:[]}),
    {io,verify:async()=>{},partialObservation:()=>({raw:'x'.repeat(32768)})}),error=>error===first&&captureEvidenceFailures(error).some(row=>row.stage==='partial-observation-encoding'));
  assert(io.files.has(memoryOutput+'.native-receipt.json'));assert.equal(io.files.has(memoryOutput),false);assert.equal(io.openHandles(),0);
});
await asyncTest('a later traversal cause is persisted completely without duplicate attachments or replacing the first panic',async()=>{
  const {graph,errors}=symbolIsolationFixture();await graph.finish();
  const later=Object.assign(new Error('later transport loss'),{code:'EPIPE',syscall:'read',path:'exact-original-path'}),first=retainStructuralFailure(graph,later),io=memoryEvidenceIo();
  assert.equal(first,errors[0]);
  await assert.rejects(persistCaptureArtifacts('oracle',memoryRoot,memoryOutput,persistencePlan,persistenceGuard(),{steps:[]},first,()=>({queries:graph.provenance().queryLog}),{io,verify:async()=>{}}),error=>error===first);
  const verified=verifyProvenanceBundle(memoryOutput,encodingLimits,io),value=decodeMemoryBundle(verified.manifest,io);
  assert.equal(value.failure.stack,first.stack);assert.equal(value.secondaryFailures.length,1);assert.equal(value.secondaryFailures[0].stage,'continued-structural-traversal');
  assert.equal(value.secondaryFailures[0].error.stack,later.stack);assert.equal(value.secondaryFailures[0].error.code,'EPIPE');assert.equal(value.secondaryFailures[0].error.syscall,'read');assert.equal(value.secondaryFailures[0].error.path,later.path);
  assert.equal(captureEvidenceFailures(first).length,1);assert.equal(io.openHandles(),0);
});
await asyncTest('held native physical close prevents partial observations as well as provenance writes',async()=>{
  const f=processFixture(),observer=observeOwnedChildClose(f.child,'native compiler helper',f.timers),io=memoryEvidenceIo(),first=retainedPanic(),guard={...persistenceGuard(),finish(){return awaitExit(f.child,30,observer);}};
  const promise=finishNativeSession(undefined,{async close(){}},guard).then(cleanup=>persistCaptureArtifacts('oracle',memoryRoot,memoryOutput,persistencePlan,guard,cleanup,first,()=>({queries:[]}),{io,verify:async()=>{},partialObservation:()=>({semanticPublicClosure:false})}));
  let settled=false;promise.then(()=>{settled=true;},()=>{settled=true;});f.exit();for(let i=0;i<8;i++)await Promise.resolve();assert.equal(settled,false);assert.equal(io.files.size,0);
  f.close();await assert.rejects(promise,error=>error===first);assert(io.files.has(memoryOutput+'.partial.json'));assert.equal(io.openHandles(),0);
});
console.log(JSON.stringify({ scope: 'root-run pure/read-only structural controls, injected process-close controls and mocked graph/provenance probes; actual compiler capture not executed by controls', requiredCheckerOperations, cases, passed: cases.filter(row => row.passed).length, failed: cases.filter(row => !row.passed).length }));
if (cases.some(row => !row.passed)) process.exitCode = 1;
