<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../PiSharp.Agent/PiSharp.Agent.csproj" />
    <ProjectReference Include="../PiSharp.Sessions/PiSharp.Sessions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PiSharp.CliSync.Tests" />
    <InternalsVisibleTo Include="PiSharp.ToolSearch.Tests" />
    <InternalsVisibleTo Include="PiSharp.Codemode.Tests" />
  </ItemGroup>
</Project>
