<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><AssemblyName>PiSharp.PiMessagesPairedComparison</AssemblyName></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/PiSharp.AI/PiSharp.AI.csproj" />
    <ProjectReference Include="../../../src/PiSharp.Contracts/PiSharp.Contracts.csproj" />
  </ItemGroup>
</Project>
