[CmdletBinding()]
param([switch]$Prepare,[Parameter(Mandatory)][string]$GrantPath,[Parameter(Mandatory)][string]$GrantSha256)
$ErrorActionPreference='Stop'
# Source-only filesystem preparation. Never invokes dotnet, a process owner, a package client or plugin code.
function Pin($path){[ordered]@{path=$path;bytes=(Get-Item -LiteralPath $path).Length;sha256=(Get-FileHash -LiteralPath $path).Hash.ToLowerInvariant()}}
function Check($pin){$actual=Pin $pin.path;if($actual.bytes-ne$pin.bytes-or$actual.sha256-cne$pin.sha256){throw 'Exact external pin differs'}}
function Read($pin){Check $pin;Get-Content -LiteralPath $pin.path -Raw|ConvertFrom-Json -AsHashtable -Depth 100 -DateKind String}
function SaveFresh($path,$value){$text=$value|ConvertTo-Json -Depth 30;$stream=[IO.File]::Open($path,'CreateNew','Write','None');$primary=$null;$secondary=$null;try{$bytes=[Text.UTF8Encoding]::new($false).GetBytes($text);$stream.Write($bytes);$stream.Flush()}catch{$primary=$_.Exception}finally{try{$stream.Dispose()}catch{$secondary=$_.Exception}};if($primary-and$secondary){throw [AggregateException]::new('Metadata write/disposal faults',[Exception[]]@($primary,$secondary))};if($primary){throw $primary};if($secondary){throw $secondary};Pin $path}
if(!$Prepare){@{status='DISABLED';nativeExecutions=0;requiresExactRootPreparationGrant=$true}|ConvertTo-Json;return}
$grantPin=Pin $GrantPath;if($grantPin.sha256-cne$GrantSha256){throw 'Exact external preparation grant required'};$g=Read $grantPin
if(!$g.preparationPermitted-or$g.executionPermitted-ne$false-or$g.credentialReadsPermitted-ne$false-or$g.networkPermitted-ne$false-or$g.packageAcquisitionPermitted-ne$false-or$g.mainWritesPermitted-ne$false){throw 'Finite private source preparation only'}
$final=Read $g.finalSourceHandoff;$leaf=Read $g.echoEntryHandoff;$finalReview=Read $g.finalSourceReview;$leafReview=Read $g.echoEntryReview
if(!$finalReview.accepted-or!$finalReview.sourceAccepted-or!$leafReview.accepted-or!$leafReview.sourceAccepted-or$final.candidate-cne$g.candidate-or$final.tree-cne$g.tree-or!$final.protectedHelperPinsCurrent){throw 'Reviewed final pinned source and independently reviewed echo entry required'}
if(![IO.Path]::IsPathFullyQualified($g.freshRoot)-or(Test-Path -LiteralPath $g.freshRoot)-or![IO.Path]::GetFullPath($g.freshRoot).StartsWith($g.workspaceRoot+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Explicit fresh task-workspace root required'}
if(!$g.privateVersion-or$g.privateVersion-cnotmatch'^0\.1\.0-private\.[a-z0-9-]+$'){throw 'Explicit bounded private build identity required'}
$sourceRows=@($final.sourcePins);$newRows=@($leaf.newSourcePins)
if(!$sourceRows.Count-or$newRows.Count-lt2){throw 'Complete final source and new leaf input inventory required'}
$all=[Collections.Generic.Dictionary[string,object]]::new([StringComparer]::Ordinal)
foreach($row in $sourceRows){if(!$all.TryAdd($row.relative,$row)){throw 'Unique complete source index required'}}
foreach($row in $newRows){if($row.relative-cnotlike'tests/PiSharp.SdkPluginEcho.Qualification.Tests/*'-and$row.relative-cnotlike'docs/source-only/sdk-plugin-echo-qualification-*'){throw 'Only disjoint owned entry/doc overlay allowed'};if(!$all.TryAdd($row.relative,$row)){throw 'No existing production/shared fixture overwrite permitted'}}
$held=[Collections.Generic.List[IO.FileStream]]::new();$primary=$null;$release=[Collections.Generic.List[Exception]]::new();$packetPin=$null
try{
 foreach($row in $all.Values){$stream=[IO.File]::Open($row.path,'Open','Read','Read');$held.Add($stream);if($stream.Length-ne$row.bytes-or[Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($stream)).ToLowerInvariant()-cne$row.sha256){throw 'Frozen source input changed'};$stream.Position=0}
 Check $g.host;Check $g.owner;Check $g.sharedOwner;Check $g.library;Check $g.runtimeManifest
 $runtime=Read $g.runtimeManifest;if($runtime.files.Count-ne7038){throw 'Existing admitted7038 private SDK required'}
 New-Item -ItemType Directory -Path $g.freshRoot|Out-Null;$cold=Join-Path $g.freshRoot 'source'
 foreach($row in $all.Values){$target=[IO.Path]::GetFullPath((Join-Path $cold $row.relative));if(!$target.StartsWith($cold+'\',[StringComparison]::OrdinalIgnoreCase)){throw 'Source copy escapes explicit private root'};New-Item -ItemType Directory -Force -Path (Split-Path -Parent $target)|Out-Null;[IO.File]::Copy($row.path,$target,$false);$copy=Pin $target;if($copy.bytes-ne$row.bytes-or$copy.sha256-cne$row.sha256){throw 'Actual source copy differs'}}
 $private=Join-Path $g.freshRoot 'private';New-Item -ItemType Directory -Path $private|Out-Null
 $offline=Join-Path $private 'NuGet.Offline.Config';[IO.File]::WriteAllText($offline,'<?xml version="1.0" encoding="utf-8"?><configuration><packageSources><clear /></packageSources><packageSourceMapping><clear /></packageSourceMapping></configuration>',[Text.UTF8Encoding]::new($false))
 $props=Join-Path $private 'Echo.Directory.Build.props';$import=[Security.SecurityElement]::Escape((Join-Path $cold 'Directory.Build.props'));$xml='<Project><Import Project="'+$import+'" /><PropertyGroup><Version>'+$g.privateVersion+'</Version><UseAppHost>false</UseAppHost><UseSharedCompilation>false</UseSharedCompilation></PropertyGroup></Project>';[IO.File]::WriteAllText($props,$xml,[Text.UTF8Encoding]::new($false))
 $targets=Join-Path $private 'Echo.Directory.Build.targets';$import=[Security.SecurityElement]::Escape((Join-Path $cold 'Directory.Build.targets'));[IO.File]::WriteAllText($targets,'<Project><Import Project="'+$import+'" /></Project>',[Text.UTF8Encoding]::new($false))
 $project=Join-Path $cold 'tests\PiSharp.SdkPluginEcho.Qualification.Tests\PiSharp.SdkPluginEcho.Qualification.Tests.csproj'
 $a=Join-Path $cold 'tests\PiSharp.SdkPluginEcho.PluginA\PiSharp.SdkPluginEcho.PluginA.csproj';$b=Join-Path $cold 'tests\PiSharp.SdkPluginEcho.PluginB\PiSharp.SdkPluginEcho.PluginB.csproj'
 $publishA=Join-Path $g.freshRoot 'publication-a';$publishB=Join-Path $g.freshRoot 'publication-b';$config=Join-Path $g.freshRoot 'root-approved-echo-config.json';$report=Join-Path $g.freshRoot 'actual-sdk-echo-report.json'
 # Package roots remain absent until genuine native publish actors; no authored lock/deps/artifacts or trust decisions.
 $properties=@((('-p:DirectoryBuildPropsPath=')+$props),(('-p:DirectoryBuildTargetsPath=')+$targets),'-p:UseSharedCompilation=false','-p:UseAppHost=false')
 $operations=@(
  @{id='lock-generation';timeoutSeconds=180;arguments=@('restore',$project,'--configfile',$offline,'--disable-parallel','--force-evaluate','-p:RestoreLockedMode=false')+$properties},
  @{id='locked-restore';timeoutSeconds=180;arguments=@('restore',$project,'--configfile',$offline,'--disable-parallel','--locked-mode','-p:RestoreLockedMode=true')+$properties},
  @{id='build';timeoutSeconds=360;arguments=@('build',$project,'-c','Release','--no-restore','--disable-build-servers','-m:1')+$properties},
  @{id='publish-a';timeoutSeconds=180;arguments=@('publish',$a,'-c','Release','--no-build','--no-restore','--output',$publishA,'--disable-build-servers')+$properties},
  @{id='publish-b';timeoutSeconds=180;arguments=@('publish',$b,'-c','Release','--no-build','--no-restore','--output',$publishB,'--disable-build-servers')+$properties},
  @{id='actual-two-echo-cases';timeoutSeconds=180;argumentsTemplate=@((Join-Path (Split-Path -Parent $project) 'bin\Release\net10.0\PiSharp.SdkPluginEcho.Qualification.Tests.dll'),'--config',$config,'--config-sha256','ROOT_APPROVED_CONFIG_SHA_AFTER_GENUINE_PUBLICATIONS','--report',$report)})
 $packet=@{status='DISABLED_PROPOSAL_REQUIRES_GENUINE_PUBLICATIONS_AND_ROOT_ADMISSION';executionPermitted=$false;candidate=$final.candidate;tree=$final.tree;echoEntry=$g.echoEntryHandoff;sourceRoot=$cold;sourceInputs=@($all.Values);host=$g.host;owner=$g.owner;sharedOwner=$g.sharedOwner;library=$g.library;runtimeManifest=$g.runtimeManifest;project=$project;operations=$operations;operationCount=6;graphCount=6;graphs=@('PiSharp.Contracts','PiSharp.Extensions.Abstractions','PiSharp.Extensions.Runtime','PiSharp.SdkPluginEcho.PluginA','PiSharp.SdkPluginEcho.PluginB','PiSharp.SdkPluginEcho.Qualification.Tests');cleanupReserveSeconds=60;budgetSeconds=1320;maximumGrantSeconds=3600;hardDeadlineUtc='2026-10-07T11:00:00Z';config=$config;configWritten=$false;publicationRoots=@($publishA,$publishB);actualPublicationCount=0;newPackageAdmissionRequired=$true;sourceApprovalCreatesNoExecutionTrust=$true;rawReport=$report;expectedCases=2;caseNames=@('sdk-plugin-echo.actual-two-loader-contexts-shared-object-mutation-and-retirement','sdk-plugin-echo.actual-held-listener-original-joins-owner-retirement');props=(Pin $props);targets=(Pin $targets);offline=(Pin $offline);locksAuthored=0;depsAuthored=0;nativeExecutions=0;remaining=@('Independent concrete packet/driver review and current complete root settlement barrier','Genuine six-graph lock generation/locked restore/build and two actual native publication outputs','Root immutable artifact manifests and separate inspection/execution decisions bound to actual shared Contracts/Abstractions','Exact final config hash and root-only runtime actor')}
 $packetPin=SaveFresh (Join-Path $g.freshRoot 'PACKET_PROPOSAL_DISABLED.json') $packet
}catch{$primary=$_.Exception}finally{foreach($stream in $held){try{$stream.Dispose()}catch{$release.Add($_.Exception)}}}
if($primary-and$release.Count){throw [AggregateException]::new('Preparation and all source lease retirement faults',[Exception[]](@($primary)+$release.ToArray()))};if($primary){throw $primary};if($release.Count){throw [AggregateException]::new('Source lease retirement faults',[Exception[]]$release.ToArray())};$packetPin|ConvertTo-Json