<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PiSharp.Cli/PiSharp.Cli.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="JsonSyntax/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
