<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PiSharp.Rpc/PiSharp.Rpc.csproj" />
    <ProjectReference Include="../../src/PiSharp.Tools/PiSharp.Tools.csproj" />
    <ProjectReference Include="../../src/PiSharp.Extensions.Runtime/PiSharp.Extensions.Runtime.csproj" />
    <ProjectReference Include="../../src/PiSharp.Extensions.Agent/PiSharp.Extensions.Agent.csproj" />
  </ItemGroup>
</Project>
