<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/PiSharp.Tools/PiSharp.Tools.csproj" />
    <ProjectReference Include="../../src/PiSharp.Tools.Skia/PiSharp.Tools.Skia.csproj" />
  </ItemGroup>
</Project>
